### ISSUE TITLE
ALERT : bug with the last H2 1.4.200

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#188]
I'm not able to isolate it, but the last H2 1.4.200 introduces nio exception when a large process is run

```java
Exception in thread "Thread-0" java.lang.AssertionError
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
	at org.h2.mvstore.MVStore.compactFile(MVStore.java:1968)
	at org.h2.mvstore.MVStore.closeStore(MVStore.java:1170)
	at org.h2.mvstore.MVStore.close(MVStore.java:1133)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:404)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1545)
	at org.h2.engine.Database.closeImpl(Database.java:1454)
	at org.h2.engine.Database.close(Database.java:1373)
	at org.h2.engine.OnExitDatabaseCloser.onShutdown(OnExitDatabaseCloser.java:85)
	at org.h2.engine.OnExitDatabaseCloser.run(OnExitDatabaseCloser.java:114)
	Suppressed: org.h2.message.DbException: GeneralError
		at org.h2.message.DbException.convert(DbException.java:352)
		at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
		at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
		at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2813)
		at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
		Suppressed: java.lang.AssertionError
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
			at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
			at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
			at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
			at org.h2.mvstore.MVStore.doMaintenance(MVStore.java:2844)
			at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2788)
			... 1 more
	Caused by: java.sql.SQLException: GeneralError
		... 5 more
	[CIRCULAR REFERENCE:java.lang.AssertionError]
```
Please execute this unit test

```java
@Test
    void testOSMGeoclimateChain() {
        String directory ="./target/geoclimate_chain"
        File dirFile = new File(directory)
        dirFile.delete()
        dirFile.mkdir()
        H2GIS datasource = H2GIS.open(dirFile.absolutePath+File.separator+"geoclimate_chain_db;AUTO_SERVER=TRUE")
        IProcess process = ProcessingChain.GeoclimateChain.OSMGeoIndicators()
        if(process.execute(datasource: datasource, placeName: "Vannes")){
            IProcess saveTables = ProcessingChain.DataUtils.saveTablesAsFiles()
            saveTables.execute( [inputTableNames: process.getResults().values()
                                 , directory: directory, datasource: datasource])
        }
    }
``` 
need for investigation

**Comment by ebocher** [comment]
Piouuuu it was a pb with the intelij cache. The code was using the 1.4.199 within functions from the last H2GIS based on 1.4.200....

**Comment by ebocher** [comment]
Not sure. I reopen it because 1.4.200 seems not very stable.
Close an reopen the database cause

```
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Fichier corrompu lors de la lecture de l'enregistrement: "nio:/home/ebocher/Autres/codes/geoclimate/processing_chain/target/geoclimate_chain/geoclimate_chain_db.mv.db". Solution possible: utiliser l'outil de récupération
File corrupted while reading record: "nio:/home/ebocher/Autres/codes/geoclimate/processing_chain/target/geoclimate_chain/geoclimate_chain_db.mv.db". Possible solution: use the recovery tool; SQL statement:
COMMENT ON ALIAS ST_MinimumBoundingCircle IS ? [90030-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
```

**Comment by katzyn** [comment]
H2 1.4.200 definitely can't always open old databases and similar issue exists in some older versions too. The recommended way to upgrade a database (with `SCRIPT TO` in previous version and `RUNSCRIPT FROM` in a new version) works well.

But if you have such corruption in the database that was created by 1.4.200 without doing weird things with it (such as usage of `Thread.interrupt()` that shouldn't be used with embedded databases unless `async:` file system is in use) it would be nice to find a test case that can reproduce such corruption.

**Comment by ebocher** [comment]
For each process a new database is created from scratch. We do not use Thread.interrupt()
I'm trying to identify a test case. It seems that the problem appears at the end of the long processing sequence.

**Comment by ebocher** [comment]
Tested with async:. The pb still exists
Exception in thread "Thread-0" java.lang.AssertionError
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)

**Comment by katzyn** [comment]
That filesystem shouldn't affect anything if you don't interrupt your threads. It may improve performance on Windows, however.

**Comment by ebocher** [comment]
fIXED
