### ISSUE TITLE
Pblm with the H2 database

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#216]
I have some troubles with the h2 database when I'm executing the BDTopoGISLayersTest.groovy file.
Here, my two tests are OK, but I have also some errors (see the second part in message)
```
/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/home/gpetit/Applications/IntelliJ/idea-IC-192.6817.14/lib/idea_rt.jar=36541:/home/gpetit/Applications/IntelliJ/idea-IC-192.6817.14/bin -Dfile.encoding=UTF-8 -classpath /home/gpetit/Applications/IntelliJ/idea-IC-192.6817.14/lib/idea_rt.jar:/home/gpetit/Applications/IntelliJ/idea-IC-192.6817.14/plugins/junit/lib/junit-rt.jar:/home/gpetit/Applications/IntelliJ/idea-IC-192.6817.14/plugins/junit/lib/junit5-rt.jar:/home/gpetit/.m2/repository/org/junit/platform/junit-platform-launcher/1.5.0-M1/junit-platform-launcher-1.5.0-M1.jar:/home/gpetit/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar:/home/gpetit/.m2/repository/org/junit/platform/junit-platform-engine/1.5.0-M1/junit-platform-engine-1.5.0-M1.jar:/home/gpetit/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar:/home/gpetit/.m2/repository/org/junit/platform/junit-platform-commons/1.5.0-M1/junit-platform-commons-1.5.0-M1.jar:/home/gpetit/Documents/Codes/geoclimate/preparedata/target/test-classes:/home/gpetit/Documents/Codes/geoclimate/preparedata/target/classes:/home/gpetit/.m2/repository/org/orbisgis/osm/1.0.0-SNAPSHOT/osm-1.0.0-20191031.085919-49.jar:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy-json/2.5.7/groovy-json-2.5.7.jar:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy/2.5.7/groovy-2.5.7.jar:/home/gpetit/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.5.0-M1/junit-jupiter-api-5.5.0-M1.jar:/home/gpetit/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.5.0-M1/junit-jupiter-engine-5.5.0-M1.jar:/home/gpetit/.m2/repository/org/orbisgis/data-manager/1.0.0-SNAPSHOT/data-manager-1.0.0-20191023.083456-32.jar:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy-sql/2.5.7/groovy-sql-2.5.7.jar:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy-templates/2.5.7/groovy-templates-2.5.7.jar:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy-xml/2.5.7/groovy-xml-2.5.7.jar:/home/gpetit/.m2/repository/org/orbisgis/data-manager-api/1.0.0-SNAPSHOT/data-manager-api-1.0.0-20191023.081723-31.jar:/home/gpetit/.m2/repository/org/locationtech/jts/jts-core/1.16.1/jts-core-1.16.1.jar:/home/gpetit/.m2/repository/org/orbisgis/commons/1.0.0-SNAPSHOT/commons-1.0.0-20191023.081707-31.jar:/home/gpetit/.m2/repository/org/orbisgis/h2gis/2.0.0-SNAPSHOT/h2gis-2.0.0-20191020.044933-13.jar:/home/gpetit/.m2/repository/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar:/home/gpetit/.m2/repository/org/orbisgis/cts/1.5.3-SNAPSHOT/cts-1.5.3-20191020.044629-12.jar:/home/gpetit/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar:/home/gpetit/.m2/repository/org/orbisgis/h2gis-api/2.0.0-SNAPSHOT/h2gis-api-2.0.0-20191020.044813-13.jar:/home/gpetit/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.10.0/jackson-core-2.10.0.jar:/home/gpetit/.m2/repository/org/orbisgis/poly2tri-core/0.1.2/poly2tri-core-0.1.2.jar:/home/gpetit/.m2/repository/org/orbisgis/h2gis-utilities/2.0.0-SNAPSHOT/h2gis-utilities-2.0.0-20191020.044833-13.jar:/home/gpetit/.m2/repository/org/orbisgis/h2gis-test-utilities/2.0.0-SNAPSHOT/h2gis-test-utilities-2.0.0-20191020.044819-13.jar:/home/gpetit/.m2/repository/org/osgi/org.osgi.service.jdbc/1.0.0/org.osgi.service.jdbc-1.0.0.jar:/home/gpetit/.m2/repository/org/orbisgis/postgis-jts/1.5.0/postgis-jts-1.5.0.jar:/home/gpetit/.m2/repository/net/postgis/postgis-jdbc/2.3.0/postgis-jdbc-2.3.0.jar:/home/gpetit/.m2/repository/org/postgresql/postgresql/9.4.1208.jre7/postgresql-9.4.1208.jre7.jar:/home/gpetit/.m2/repository/org/orbisgis/postgis-jts-osgi/2.0.0-SNAPSHOT/postgis-jts-osgi-2.0.0-20191023.082249-16.jar:/home/gpetit/.m2/repository/org/orbisgis/process-manager/1.0.0-SNAPSHOT/process-manager-1.0.0-20191023.081831-31.jar:/home/gpetit/.m2/repository/org/orbisgis/process-manager-api/1.0.0-SNAPSHOT/process-manager-api-1.0.0-20191023.081817-31.jar:/home/gpetit/.m2/repository/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar:/home/gpetit/.m2/repository/org/slf4j/slf4j-simple/1.7.26/slf4j-simple-1.7.26.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit5 org.orbisgis.orbisprocess.geoclimate.preparedata.bdtopo.BDTopoGISLayersTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/gpetit/.m2/repository/org/codehaus/groovy/groovy/2.5.7/groovy-2.5.7.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[main] INFO org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Executing the importPreprocess.sql script
[main] INFO org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - The importPreprocess.sql script has been executed


[main] INFO org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Executing the typesMatching.sql script
[main] INFO org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - The typesMatching.sql script has been executed

Exception in thread "Thread-0" java.lang.AssertionError
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
	at org.h2.mvstore.MVStore.compactFile(MVStore.java:1968)
	at org.h2.mvstore.MVStore.closeStore(MVStore.java:1170)
	at org.h2.mvstore.MVStore.close(MVStore.java:1133)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:404)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1545)
	at org.h2.engine.Database.closeImpl(Database.java:1454)
	at org.h2.engine.Database.close(Database.java:1373)
	at org.h2.engine.OnExitDatabaseCloser.onShutdown(OnExitDatabaseCloser.java:85)
	at org.h2.engine.OnExitDatabaseCloser.run(OnExitDatabaseCloser.java:114)

Process finished with exit code 0
```
Let's assume it's OK. So now I want to open the database (which is here `/.../geoclimate/preparedata/target/h2gis_bd_topo_gis_layer_c2283554-9b54-4249-9da2-0d1c3d0a9217.mv.db` (337mb)
In DBeaver, I have this error message
```
org.h2.jdbc.JdbcSQLException: Row {1} not found in primary index "PUBLIC.SYS_DATA: 510" [90143-197]
Row {1} not found in primary index "PUBLIC.SYS_DATA: 510" [90143-197]
```
(and the test before, I had a message about a CREATE CACHED TABLE "public"."IRIS_GE" ....)

Then, if I try to open this db in OG 5.1, it works but I only have some of the tables (e.g input_veget and input_hydro are not here. Same for all the input tables from BD Topo).

Then, if I try to open this db in H2GIS 2.0 (direct download from Jenkins), I have this error message 
```
Erreur générale: "java.lang.IllegalStateException: Unable to read the page at position 87686052466449 [1.4.200/6]"
General error: "java.lang.IllegalStateException: Unable to read the page at position 87686052466449 [1.4.200/6]" [50000-200] HY000/50000 (Aide)
org.h2.jdbc.JdbcSQLNonTransientException: Erreur générale: "java.lang.IllegalStateException: Unable to read the page at position 87686052466449 [1.4.200/6]"
General error: "java.lang.IllegalStateException: Unable to read the page at position 87686052466449 [1.4.200/6]" [50000-200]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
    at org.h2.message.DbException.get(DbException.java:194)
    at org.h2.message.DbException.convert(DbException.java:347)
    at org.h2.engine.Database.openDatabase(Database.java:333)
    at org.h2.engine.Database.<init>(Database.java:301)
    at org.h2.engine.Engine.openSession(Engine.java:74)
    at org.h2.engine.Engine.openSession(Engine.java:192)
    at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
    at org.h2.engine.Engine.createSession(Engine.java:166)
    at org.h2.engine.Engine.createSession(Engine.java:29)
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
    at org.h2.Driver.connect(Driver.java:69)
    at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
    at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
    at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
    at org.h2.server.web.WebApp.test(WebApp.java:947)
    at org.h2.server.web.WebApp.process(WebApp.java:238)
    at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
    at org.h2.server.web.WebThread.process(WebThread.java:139)
    at org.h2.server.web.WebThread.run(WebThread.java:94)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to read the page at position 87686052466449 [1.4.200/6]
    at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
    at org.h2.mvstore.MVStore.readPage(MVStore.java:2213)
    at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
    at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:688)
    at org.h2.mvstore.MVMap.setRootPos(MVMap.java:682)
    at org.h2.mvstore.MVStore.openMap(MVStore.java:576)
    at org.h2.mvstore.MVStore.openMap(MVStore.java:535)
    at org.h2.mvstore.MVStore.openMap(MVStore.java:516)
    at org.h2.mvstore.MVStore.removeMap(MVStore.java:2742)
    at org.h2.engine.Database.handleUpgradeIssues(Database.java:866)
    at org.h2.engine.Database.open(Database.java:742)
    at org.h2.engine.Database.openDatabase(Database.java:307)
    ... 19 more
Caused by: java.lang.IllegalStateException: Unsupported type 17 [1.4.200/3]
    at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
    at org.h2.mvstore.type.ObjectDataType.newType(ObjectDataType.java:165)
    at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:229)
    at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:114)
    at org.h2.mvstore.Page.read(Page.java:605)
    at org.h2.mvstore.Page.read(Page.java:239)
    at org.h2.mvstore.MVStore.readPage(MVStore.java:2211)
    ... 29 more
```
I can't see if the problem is coming from me or from H2. Especially since the tests in InterlliJ are OK.

Any idea @ebocher @SPalominos @j3r3m1 ?

**Comment by ebocher** [comment]
seems fixed with the last H2 master used by H2GIS @SPalominos  ?

**Comment by ebocher** [comment]
Fixed
