### ISSUE TITLE
Workflow OSM - Boston

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#261]
```java
org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChainOSMTest,testOSMWorkflowFromPlaceName
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Building OSM GIS layers
[INFO] org.orbisgis.osm.Utilities - https://nominatim.openstreetmap.org/search?q=Boston&limit=5&format=geojson&polygon_geojson=1
[INFO] org.orbisgis.osm.Utilities - Executing query... Boston
[INFO] org.orbisgis.osm.Utilities - Downloading the Nominatim data.
[INFO] org.orbisgis.osm.Loader - Extract the OSM data
[INFO] org.orbisgis.osm.Loader - https://overpass-api.de/api/interpreter?data=%5Bmaxsize%3A1073741824%5D%3B%28%28node%2842.2279112%2C-71.1912491%2C42.3969775%2C+-70.8044881%29%3Bway%2842.2279112%2C-71.1912491%2C42.3969775%2C+-70.8044881%29%3Brelation%2842.2279112%2C-71.1912491%2C42.3969775%2C+-70.8044881%29%3B%29%3B%3E%3B%29%3Bout%3B
[INFO] org.orbisgis.osm.Loader - Executing query... [maxsize:1073741824];((node(42.2279112,-71.1912491,42.3969775, -70.8044881);way(42.2279112,-71.1912491,42.3969775, -70.8044881);relation(42.2279112,-71.1912491,42.3969775, -70.8044881););>;);out;
[INFO] org.orbisgis.osm.Loader - Downloading the OSM data from overpass api in /tmp/extract_osm4313006087509014431.osm
[INFO] org.orbisgis.osm.Loader - The OSM file has been downloaded at /tmp/extract_osm4313006087509014431.osm.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Loading
[INFO] org.orbisgis.osm.Loader - Load the OSM file in the database.
[INFO] org.orbisgis.osm.Loader - The input OSM file has been loaded in the database.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the building layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Start polygons transformation
[INFO] org.orbisgis.osm.utils.TransformUtils - Indexing osm tables...
[INFO] org.orbisgis.osm.utils.TransformUtils - Build way polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build all polygon relations
[INFO] org.orbisgis.osm.utils.TransformUtils - The way and relation POLYGONS have been built.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Building layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the road layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Build ways as lines
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Road layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the rail layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Build ways as lines
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Rail layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the vegetation layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Start polygons transformation
[INFO] org.orbisgis.osm.utils.TransformUtils - Indexing osm tables...
[INFO] org.orbisgis.osm.utils.TransformUtils - Build way polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build all polygon relations
[INFO] org.orbisgis.osm.utils.TransformUtils - The way and relation POLYGONS have been built.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Vegetation layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the water layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Start polygons transformation
[INFO] org.orbisgis.osm.utils.TransformUtils - Indexing osm tables...
[INFO] org.orbisgis.osm.utils.TransformUtils - Build way polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build all polygon relations
[INFO] org.orbisgis.osm.utils.TransformUtils - The way and relation POLYGONS have been built.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Water layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Create the impervious layer
[INFO] org.orbisgis.osm.utils.TransformUtils - Start polygons transformation
[INFO] org.orbisgis.osm.utils.TransformUtils - Indexing osm tables...
[INFO] org.orbisgis.osm.utils.TransformUtils - Build way polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode outer polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Explode inner polygons
[INFO] org.orbisgis.osm.utils.TransformUtils - Build all polygon relations
[INFO] org.orbisgis.osm.utils.TransformUtils - The way and relation POLYGONS have been built.
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - impervious layer created
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - OSM GIS layers created
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Formating OSM GIS layers
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Formating building layer
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Buildings transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Formating road layer
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Roads transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Rails transformation starts
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Rails transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Vegetation transformation starts
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Vegetation transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Hydro transformation starts
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Hydro transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Impervious transformation starts
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - OSM_POLYGONS_618a7ec3_5eb3_4ee0_9f43_760b3d9b7cf0
[INFO] org.orbisgis.orbisprocess.geoclimate.preparedata.PrepareData - Impervious transformation finishes
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - OSM GIS layers formated
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Start computing the geoindicators...
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Create the units of analysis...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing the abstract model to build the RSU
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing vegetation...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing hydrographic...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing road...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Preparing rail...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Grouping all tables...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - RSU created...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the reference spatial units
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Reference spatial units table created
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the blocks...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Building index to perform the process...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Building spatial clusters...
[INFO] gui.class org.h2gis.network.functions.GraphCreator - Loading graph into memory...
[INFO] gui.class org.h2gis.network.functions.GraphCreator -     0.013 seconds
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents - Calculating connected components... 
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.001 seconds
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents - Storing node connected components... 
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.001 seconds
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents - Storing edge connected components...
[INFO] gui.class org.h2gis.network.functions.ST_ConnectedComponents -     0.003 seconds
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Merging spatial clusters...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the block table...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - The blocks have been created
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the Tables of relations between two scales
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - The relations between scales have been created
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the Tables of relations between two scales
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - The relations between scales have been created
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Creating the Tables of relations between two scales
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - The relations between scales have been created
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Start computing building indicators...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Geometry properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building size properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building interactions properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building form properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building minimum building spacing
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building road distance
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Utility process to join tables in one
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Building closeness to a 50 m wide building
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Utility process to join tables in one
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Start computing block indicators...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Unweighted statistical operations from lower scale
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Hole area ratio
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Perkins skill score building direction
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Closingness of a block
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Block net net_compactness
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Weighted statistical operations from lower scale
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Utility process to join tables in one
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Start computing RSU indicators...
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Geometry properties
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing RSU free external facade density
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Unweighted statistical operations from lower scale
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing road fraction
[ERROR] org.orbisgis.orbisdata.processmanager.process.Process - Error while executing the process.
Exception lors de l'appel de la fonction définie par l'utilisateur: "intersection(MULTIPOLYGON (((-82.26330262006508 47.12365513859813, -82.84862398826823 45.460065727193616, -82.63255722433222 46.170948597004696, -82.63254382433222 46.1709882970047, -82.29109012837529 47.065196199878145, -82.29107272837527 47.065236899878144, -82.26330262006508 47.12365513859813)), ((-82.24914890154176 47.153429430373855, -81.87482005597602 47.94088159353359, -81.87479805597602 47.94092349353359, -81.3748732775481 48.8051704479454, -81.37484637754811 48.8052128479454, -80.33769965875085 50.20728985332498, -80.33766435875084 50.20733105332498, -71.07241257208283 42.26889930205139, -82.24914890154176 47.153429430373855)), ((-60.03225664247099 37.44405842990588, -60.03213281000496 37.44425584938214, -59.894119695130016 37.383940458749414, -59.89421199513001 37.38372925874941, -60.03225664247099 37.44405842990588)), ((-61.92301195368799 34.42972838187203, -61.80862904124915 34.33172554667502, -61.808664341249155 34.33168434667502, -61.9230411024683 34.42968191153088, -61.92301195368799 34.42972838187203))), POLYGON ((-71.168 42.355, -71.169 42.355, -71.17 42.355, -71.171 42.355, -71.172 42.355, -71.17133333112574 42.35566666887426, -71.174 42.353, -71.174 42.354, -71.174 42.355, -71.174 42.356, -71.175 42.356, -71.175 42.357, -71.176 42.357, -71.177 42.358, -71.176 42.358, -71.175 42.358, -71.174 42.358, -71.173 42.357, -71.172 42.357, -71.171 42.357, -71.171 42.356, -71.17 42.356, -71.169 42.356, -71.168 42.356, -71.167 42.356, -71.167 42.355, -71.167 42.354, -71.168 42.355))): found non-noded intersection between LINESTRING ( -71.171 42.355, -71.172 42.355 ) and LINESTRING ( -71.17133333112574 42.35566666887426, -71.1724171575047 42.3545828424953 ) [ (-71.172, 42.355, NaN) ]"
Exception calling user-defined function: "intersection(MULTIPOLYGON (((-82.26330262006508 47.12365513859813, -82.84862398826823 45.460065727193616, -82.63255722433222 46.170948597004696, -82.63254382433222 46.1709882970047, -82.29109012837529 47.065196199878145, -82.29107272837527 47.065236899878144, -82.26330262006508 47.12365513859813)), ((-82.24914890154176 47.153429430373855, -81.87482005597602 47.94088159353359, -81.87479805597602 47.94092349353359, -81.3748732775481 48.8051704479454, -81.37484637754811 48.8052128479454, -80.33769965875085 50.20728985332498, -80.33766435875084 50.20733105332498, -71.07241257208283 42.26889930205139, -82.24914890154176 47.153429430373855)), ((-60.03225664247099 37.44405842990588, -60.03213281000496 37.44425584938214, -59.894119695130016 37.383940458749414, -59.89421199513001 37.38372925874941, -60.03225664247099 37.44405842990588)), ((-61.92301195368799 34.42972838187203, -61.80862904124915 34.33172554667502, -61.808664341249155 34.33168434667502, -61.9230411024683 34.42968191153088, -61.92301195368799 34.42972838187203))), POLYGON ((-71.168 42.355, -71.169 42.355, -71.17 42.355, -71.171 42.355, -71.172 42.355, -71.17133333112574 42.35566666887426, -71.174 42.353, -71.174 42.354, -71.174 42.355, -71.174 42.356, -71.175 42.356, -71.175 42.357, -71.176 42.357, -71.177 42.358, -71.176 42.358, -71.175 42.358, -71.174 42.358, -71.173 42.357, -71.172 42.357, -71.171 42.357, -71.171 42.356, -71.17 42.356, -71.169 42.356, -71.168 42.356, -71.167 42.356, -71.167 42.355, -71.167 42.354, -71.168 42.355))): found non-noded intersection between LINESTRING ( -71.171 42.355, -71.172 42.355 ) and LINESTRING ( -71.17133333112574 42.35566666887426, -71.1724171575047 42.3545828424953 ) [ (-71.172, 42.355, NaN) ]"; SQL statement:
CREATE TABLE interTablea2dccd4f_7634_4243_a051_995762adb309 AS SELECT b.id_rsu, a.zindex, ST_AREA(b.the_geom) AS RSU_AREA, ST_AREA(ST_INTERSECTION(a.the_geom, b.the_geom)) AS ROAD_AREA FROM surfTable9098bf6d_d245_4c01_9370_01b158cb005f a, rsu b WHERE a.the_geom && b.the_geom AND ST_INTERSECTS(a.the_geom, b.the_geom); [90105-200]
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Cannot compute the fraction of road for the RSU
[ERROR] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Cannot compute the RSU indicators
[ERROR] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Cannot build the geoindicators
Exception in thread "Thread-1" java.lang.AssertionError
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
	at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2007)
	at org.h2.mvstore.MVStore.compactFile(MVStore.java:1968)
	at org.h2.mvstore.MVStore.closeStore(MVStore.java:1170)
	at org.h2.mvstore.MVStore.close(MVStore.java:1133)
	at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:404)
	at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1545)
	at org.h2.engine.Database.closeImpl(Database.java:1454)
	at org.h2.engine.Database.close(Database.java:1373)
	at org.h2.engine.OnExitDatabaseCloser.onShutdown(OnExitDatabaseCloser.java:85)
	at org.h2.engine.OnExitDatabaseCloser.run(OnExitDatabaseCloser.java:114)
	Suppressed: org.h2.message.DbException: GeneralError
		at org.h2.message.DbException.convert(DbException.java:352)
		at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
		at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
		at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2813)
		at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)
		Suppressed: java.lang.AssertionError
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:616)
			at org.h2.mvstore.MVMap.rewritePage(MVMap.java:775)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:734)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
			at org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
			at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
			at org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
			at org.h2.mvstore.MVStore.doMaintenance(MVStore.java:2844)
			at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2788)
			... 1 more
	Caused by: java.sql.SQLException: GeneralError
		... 5 more
	[CIRCULAR REFERENCE:java.lang.AssertionError]

Process finished with exit code 0

```

**Comment by j3r3m1** [comment]
it seems we also have trouble with non valid geometries in OSM =)

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
Done here https://github.com/orbisgis/geoclimate/pull/268
Boston processed in 30 minutes
