### ISSUE TITLE
Unable to execute OSM workflow

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#279]
Hi, I'm trying to play with the OSM workflow (placename --> output folder).
So in the DBeaver groovy console, I executed the following script 

```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')
import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger
def process = geoclimate.workflow.OSM()
process.execute(['/home/gpetit/geoclimate/osm/config.json'])
logger.info process.results.outputMessage
```

and with the following configuration file

```json
{
    "description" :"Conf file to run the OSM workflow and store the resultst in a folder",
    "geoclimatedb" : {
        "path" : "/home/gpetit/geoclimate/osm/db/geoclimate_db;AUTO_SERVER=TRUE",
        "delete" :true
    },
    "input" : {
        "osm" : ["vannes"]},
    "output" :{
     "folder" : "/home/gpetit/geoclimate/osm/"},
    "parameters":
    {"distance" : 1000,
        "indicatorUse": ["LCZ", "URBAN_TYPOLOGY", "TEB"],
        "svfSimplified": false,
        "prefixName": "",
        "mapOfWeights":
        {"sky_view_factor": 1,
            "aspect_ratio": 1,
            "building_surface_fraction": 1,
            "impervious_surface_fraction" : 1,
            "pervious_surface_fraction": 1,
            "height_of_roughness_elements": 1,
            "terrain_roughness_class": 1},
        "hLevMin": 3,
        "hLevMax": 15,
        "hThresholdLev2": 10
    }
}
```

But I got this error log
```bash
!SESSION 2020-02-18 11:32:39.419 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Command-line arguments:  -data file:/home/gpetit/.local/share/DBeaverData/workspace6/ -os linux -ws gtk -arch x86_64

!ENTRY org.orbisgis.ui.editors.groovy.GroovyJob 4 0 2020-02-18 11:38:48.278
!MESSAGE Error while execution the Groovy script.
!STACK 0
groovy.lang.MissingPropertyException: No such property: geoclimate for class: Script
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
	at Script.run(Script.groovy:7)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:570)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)
```

Any idea @ebocher @SPalominos ?

**Comment by ebocher** [comment]
try 
def process = geoclimate.workflow.OSM()
process.execute(configurationFile:  '/home/gpetit/geoclimate/osm/config.json')

**Comment by gpetit** [comment]
Hum still the same error with 

```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

def process = geoclimate.workflow.OSM()
process.execute(configurationFile:'/home/gpetit/geoclimate/osm/config.json')
                   
logger.info process.results.outputMessage
```

I also tried with double quote `process.execute(configurationFile:"/home/gpetit/geoclimate/osm/config.json")`

**Comment by ebocher** [comment]
I will check

**Comment by ebocher** [comment]
The methods are case sensitive so write
Geoclimate.Workflow.OSM() instead of geoclimate.workflow.OSM()

**Comment by gpetit** [comment]
Thanks for your help. New error message with 
```groovy
def process = Geoclimate.Workflow.OSM
process.execute(configurationFile:"/home/gpetit/geoclimate/osm/config.json")
```

```
groovy.lang.MissingPropertyException: No such property: OSM for class: org.orbisgis.orbisprocess.geoclimate.processingchain.Workflow
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at Script.run(Script.groovy:7)
	at groovy.util.GroovyScriptEngine.run(GroovyScriptEngine.java:570)
	at org.orbisgis.ui.editors.groovy.GroovyJob$GroovyRunnable.run(GroovyJob.java:133)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ebocher** [comment]
Sorry bad copy-paste
try
Geoclimate.Workflow.OSM()

**Comment by gpetit** [comment]
Hum we are progressing ... but I should miss something.
Now with your correction, the groovy scripts works ... but it ends in less than half-second and there is no output files.

I the meantime, I was wondering if the working db should be created before ? I tried to create it by hand before and reexecuted the script, but still the same

![image](https://user-images.githubusercontent.com/1871248/74740375-09509900-525b-11ea-98c8-4566de326626.png)

**Comment by ebocher** [comment]
Are you working with the last geoclimate library ?
I run this config file without any pb
```json
{
    "description" :"Example of configuration file to process OSM DATA and save results in a folder",
    "geoclimatedb" : {
        "path" : "/tmp/vannes/geoclimate_db;AUTO_SERVER=TRUE",
        "delete" :true
    },
    "input" : {
         "osm" : ["kerfot"]
    },
    "output" :{
     "folder" : {"path": "/tmp/vannes",
         "tables": ["building_indicators",
             "block_indicators",
             "rsu_indicators",
             "rsu_lcz",
             "zones",
             "building",
             "road",
             "rail" ,
             "water",
             "vegetation",
             "impervious"]}},
    "parameters":
    {"distance" : 1000,
        "indicatorUse": ["TEB"],
        "svfSimplified": false,
        "prefixName": "",
        "mapOfWeights":
        {"sky_view_factor": 1,
            "aspect_ratio": 1,
            "building_surface_fraction": 1,
            "impervious_surface_fraction" : 1,
            "pervious_surface_fraction": 1,
            "height_of_roughness_elements": 1,
            "terrain_roughness_class": 1},
        "hLevMin": 3,
        "hLevMax": 15,
        "hThresholdLev2": 10
    }
}
```
I will test your file

**Comment by ebocher** [comment]
It runs without any pbs
Below is an extract of the log system
```java
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Perviousness fraction
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing RSU effective terrain roughness length
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing RSU effective terrain roughness class
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Perkins skill score building direction
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Executing Utility process to join tables in one
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Geoindicators calculation time: 164.088 s
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - All geoindicators have been computed
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - Set the LCZ type of each RSU
[INFO] org.orbisgis.orbisprocess.geoclimate.geoindicators.Geoindicators - The LCZ classification has been performed.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - vannes has been processed
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - building_indicators has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - block_indicators has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - rsu_indicators has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - RSU_LCZ has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - ZONE_0d08186c_1a99_4703_be2a_0aba1941945a has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_BUILDING_fad9d16d_fac0_4970_a290_0876397480d2 has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_ROAD_73cfa362_1aff_4212_8d52_175a8604ccef has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_RAILS_607e93e8_cc38_47ba_a630_9476604442fc has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_HYDRO_3f428371_b830_4e36_be40_660814115d3a has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_VEGET_e857294f_540d_41a8_8af5_da6d31aa9f6f has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - INPUT_IMPERVIOUS_926c729c_b22f_4c33_ae73_027a25f7a4aa has been saved.
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - Number of areas processed 1 on 1
[INFO] org.orbisgis.orbisprocess.geoclimate.processingchain.ProcessingChain - The local H2GIS database has been deleted
The vannes have been processed
```

**Comment by gpetit** [comment]
> Are you working with the last geoclimate library ?

Good question.
How to know the Geoclimate version ?
If I play the role of a simple user, it seems to me that by writing the following lines I should automatically be on the latest Geoclimate version. No ?


```groovy
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
...
```

Can you tell me if your `/tmp/vannes/geoclimate_db` was already created before launching the script ?

In the same time, my Groovy editor is up-to-date

**Comment by ebocher** [comment]
The folder /tmp/vannes/geoclimate_db is created automatically but the input and output folders must exist

**Comment by gpetit** [comment]
Ok so I removed my db. And my output folder is already created. I don't have any input folder since I'm trying the OSM workflow --> output folder.
The problem should not come from the config file ... but more on the Groovy side.
Can you give me your groovy file that you used to execute the script ?

**Comment by ebocher** [comment]
```
@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.orbisprocess', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.orbisprocess.geoclimate.Geoclimate
Geoclimate.logger = logger

def process = Geoclimate.Workflow.OSM()
process.execute(configurationFile:'/tmp/config.json')
                   
logger.info process.results.outputMessage
```

**Comment by j3r3m1** [comment]
For information, if I use the script of @ebocher and the config file of @gpetit it works well in the groovyConsole.

**Comment by SPalominos** [comment]
Issue caused by the `.groovy` cache which was keeping old dependencies version using `groovy-3.0.0-rc2`.
