### ISSUE TITLE
URBAN_TYPOLOGY parameter leading to an error

### ISSUE THREAD

**Issue by ernlt** [orbisgis/geoclimate#506]
I am running the chain with the following configuration file for OSM workflow:
```
       "geoclimatedb" : [
                "folder" :"/tmp/osm/",
                "name" : "geoclimate_db;AUTO_SERVER=TRUE",
                "delete" : true
        ],
        "input" : [
                "osm" : ["vannes"]
        ],
        "output" : [
            "folder" : "/tmp/osm/", 
            "tables": [
                "block_indicators",
                "building",
                "building_indicators",
                "impervious",
                "rail",
                "road",
                "rsu_indicators",
                "rsu_lcz",
                "vegetation",
                "water", 
                "zones",
            ]
        ],
        "parameters": [
                "distance": 0,
                "indicatorUse": ["LCZ","URBAN_TYPOLOGY"],
                "svfSimplified": false,
                "prefixName": "",
                "hLevMin": 3,
                "hLevMax": 15,
                "hThresholdLev2": 10,
                "estimatedHeight": true,
                "grid_indicators": [
                    "x_size": 1000,
                    "y_size": 1000,
                    "indicators": ["BUILDING_MEAN_HEIGHT"]
	        ]
        ]
```

An error occurs when specifying the "URBAN_TYPOLOGY" parameter above:
```
[INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory -  The URBAN TYPOLOGY classification is performed 
[INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory -  Executing the gathering of scales (to building or to RSU scale)
[INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory - Executing Unweighted statistical operations from lower scale
[INFO] org.orbisgis.orbisdata.processmanager.process.GroovyProcessFactory - Apply a Random Forest model
Caught: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserException
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:369)
	at org.orbisgis.orbisprocess.geoclimate.geoindicators.TypologyClassification$_applyRandomForestModel_closure3$_closure11.doCall(TypologyClassification.groovy:593)
```

**Comment by ebocher** [comment]
"grid_indicators" is not yet implemented. I'm on it. The PR is as a draft statut

**Comment by ernlt** [comment]
I also made a test without using the "grid_indicators" parameter and still have the error. Maybe it is better to wait for the PR to be completed and then come back to this issue.
