### ISSUE TITLE
Groovy version problem

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#513]
I've been updating my Groovy version from 2.5.2 to 3.0.7.
With this version, if I try to execute the script provided by Erwan (which works well for him),
I get the following error :

groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.7 and you are trying to load version 3.0.0

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

@SPalominos, is it possible to upgrade from 3.0.4 to 3.0.7 on your side ?

**Comment by ebocher** [comment]
Solved we are now in 3.0.7
