### ISSUE TITLE
Chain crashing for some areas during application of the building_height_osm_rf_2_0.model

### ISSUE THREAD

**Issue by ELSW56** [orbisgis/geoclimate#550]
It happens several time: I'll give the other bboxes concerned in further comments.
Here's the errors stack trace associated for the zone [53.41396, 5.33682, 53.49729, 5.42015]:
```
All geoindicators have been computed
Extracting the building having no height information and estimate it
Collect building indicators to estimate the height
Start estimating the building height
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
Error while executing the process.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
	at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:226) ~[geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at smile.data.DataFrame.of(DataFrame.java:1230) ~[geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame.of(DataFrame.java:1019) ~[geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame$of.call(Unknown Source) ~[?:?]
	at org.orbisgis.orbisprocess.geoclimate.geoindicators.TypologyClassification$_applyRandomForestModel_closure3$_closure11.doCall(TypologyClassification.groovy:664) ~[geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor553.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisprocess.geoclimate.processingchain.GeoIndicatorsChain$_computeAllGeoIndicators_closure5$_closure18.doCall(GeoIndicatorsChain.groovy:1123) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor925.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisprocess.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure22$_closure23.doCall(WorkflowOSM.groovy:618) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor914.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2234) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2214) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2264) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisprocess.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure22.doCall(WorkflowOSM.groovy:453) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor388.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisprocess.geoclimate.osm.WorkflowOSM$_workflow_closure1$_closure19.doCall(WorkflowOSM.groovy:321) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor382.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [groovy-3.0.7.jar:3.0.7]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [groovy-3.0.7.jar:3.0.7]
	at slim_europe_processing_v3_els.run(slim_europe_processing_v3_els.groovy:125) [shell:?]
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:254) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyShell.run(GroovyShell.java:360) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyShell.run(GroovyShell.java:339) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyShell.run(GroovyShell.java:166) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.GroovyShell$run$0.call(Unknown Source) [groovy-3.0.7.jar:?]
	at groovy.console.ui.Console$_runScriptImpl_closure22.doCall(Console.groovy:1302) [groovy-console-3.0.7.jar:3.0.7]
	at groovy.console.ui.Console$_runScriptImpl_closure22.doCall(Console.groovy) [groovy-console-3.0.7.jar:3.0.7]
	at jdk.internal.reflect.GeneratedMethodAccessor903.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [groovy-3.0.7.jar:3.0.7]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:412) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.call(Closure.java:406) [groovy-3.0.7.jar:3.0.7]
	at groovy.lang.Closure.run(Closure.java:493) [groovy-3.0.7.jar:3.0.7]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Cannot apply the building height model BUILDING_HEIGHT_OSM_RF_2_0.model
Cannot build the geoindicators for the zone [53.41396, 5.33682, 53.49729, 5.42015]

```

**Comment by ELSW56** [comment]
Here's the config file content (except "input" "osm" value it will be the same for all the zones concerned) :
```
{
    "description": "Run the Geoclimate chain with OSM data and export result to a folder",
    "geoclimatedb": {
        "folder": "D:/Users/le_sauxe/Documents/IUT/Recherche/Labsticc/SLIM/geoclimate_chain2",
        "name": "slim_1616577824508;AUTO_SERVER=TRUE",
        "delete": true
    },
    "input": {
        "osm": [
            [
                53.41396,
                5.33682,
                53.49729,
                5.42015
            ]
        ],
        "delete": true
    },
    "output": {
        "folder": {
            "path": "D:/Users/le_sauxe/Documents/IUT/Recherche/Labsticc/SLIM/geoclimate_chain2",
            "tables": [
                "zones",
                "rsu_indicators",
                "rsu_lcz",
                "grid_indicators"
            ]
        },
        "srid": 4326
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        },
        "grid_indicators": {
            "x_size": 10,
            "y_size": 10,
            "rowCol": true,
            "output": "asc",
            "indicators": [
                "BUILDING_FRACTION",
                "BUILDING_HEIGHT",
                "WATER_FRACTION",
                "VEGETATION_FRACTION",
                "ROAD_FRACTION",
                "IMPERVIOUS_FRACTION",
                "LCZ_FRACTION"
            ]
        }
    }
}
```

**Comment by j3r3m1** [comment]
The input table used as input of the RF was empty. The reason was that there was only one building in the area, which already has a building height. Thus it was not added to the table used as input of the RF, resulting in an empty table.
I have added a test on the input table to see if it is empty (#553). It solves the problem on the area proposed.
