### ISSUE TITLE
Running geoclimate failed

### ISSUE THREAD

**Issue by 4estone** [orbisgis/geoclimate#595]
Running C:\temp\LCZ\orbisgis>java -jar geoclimate.jar -f strasbourg.json

Maybe need network params? Nothing about that in doc

Error while executing the process.
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_101]
        at java.net.SocketInputStream.read(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.InputRecord.readFully(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.InputRecord.read(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_101]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[?:1.8.0_101]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl$connect.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130) ~[geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.executeNominatimQuery(Utilities.groovy:229) ~[geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$executeNominatimQuery$0.callStatic(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240) ~[geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.getAreaFromPlace(Utilities.groovy:84) ~[geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$getAreaFromPlace.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM.extractOSMZone(WorkflowOSM.groovy:755) ~[geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure19$_closure20.doCall(WorkflowOSM.groovy:458) ~[geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2234) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2214) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2264) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure19.doCall(WorkflowOSM.groovy:455) ~[geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_workflow_closure1$_closure16.doCall(WorkflowOSM.groovy:323) [geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) [geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:74) [geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [geoclimate.jar:?]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [geoclimate.jar:?]
        at picocli.CommandLine.access$1200(CommandLine.java:145) [geoclimate.jar:?]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [geoclimate.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [geoclimate.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [geoclimate.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [geoclimate.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:2058) [geoclimate.jar:?]
        at picocli.CommandLine$execute.call(Unknown Source) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [geoclimate.jar:?]
Cannot import the file : C:\Users\SYLVAI~1.PIE\AppData\Local\Temp\\logzones.geojson
Cannot execute the OSM workflow

**Comment by 4estone** [comment]
My con file looks like:
`{
    "description": "Processing OSM data",
    "input": {
        "osm": [
            "strasbourg"
        ]
    },
    "output": {
        "folder": "c:\\temp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": true,
            "estimateHeight": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}`

**Comment by j3r3m1** [comment]
Hi,
Did you get an error when executing this command ?
```bash
java -jar geoclimate.jar -h
```

**Comment by 4estone** [comment]
No

**Comment by j3r3m1** [comment]
It may come from the OSM API. Did you try using a smaller city (with low inhabitant number and small territory) ?

**Comment by ebocher** [comment]
Hi,
Another issue could to be related to a proxy that locks the access to external network.

**Comment by 4estone** [comment]
Do you have more information to deal with a proxy issue? 
Is it possible to run  geocimate with args like this:[http://alomax.free.fr/extras/java_proxy_fireeall.html](url)

**Comment by 4estone** [comment]
Got it running!
`java -Dhttp.proxyHost=<myproxyHost> -Dhttp.proxyPort=8080 -Dhttp.proxyUser=<proxyuser> -Dhttp.proxyPassword=<proxypasswd> -jar geoclimate.jar -f strasbourg.json`
Got an error at the end of processing:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:320)
        at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:226)
        at smile.data.DataFrame.of(DataFrame.java:1230)
        at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame.of(DataFrame.java:1019)
        at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame$of.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.geoindicators.TypologyClassification$_applyRandomForestModel_closure3$_closure11.doCall(TypologyClassification.groovy:677)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300)
        at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819)
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416)
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)

**Comment by j3r3m1** [comment]
If you increase the memory allocated to JAVA, does it work (add -Xmx2048m after java in the command line) ?

**Comment by 4estone** [comment]
"The OSM workflow has been successfully executed" with Xmx1g.

If I want to process (eg: a french departement) what is the best way to proceed? By tils instead of adminstrative boundaries?

**Comment by j3r3m1** [comment]
Yes ideally using a list of bounding boxes :
- will cost you less memory than running the entire department at once
- will avoid to run several times a territory since when we make the calculation on a given city we take a bounding box which encompasses the surrounding territories

**Comment by 4estone** [comment]
Thanks for tips.
is there any better bounding box size? (eg: does the size change time processing ?)

**Comment by j3r3m1** [comment]
The optimized size probably depends on territory complexity so hard to give an answer valid for everywhere. 10 km worked quite well for us.
Anyway it seems your issue is solved. If so, do not forget to close the issue. Thanks !

**Comment by 4estone** [comment]
Both issues solved with 
 `java -Xmx1g  -Dhttp.proxyHost=<yourproxyHost> -Dhttp.proxyPort=8080 -Dhttp.proxyUser=<proxyuser> -Dhttp.proxyPassword=<proxypasswd> -jar geoclimate.jar -f strasbourg.json`
