### ISSUE TITLE
Error with bounding box case with BDTOPO (Linux and Windows)

### ISSUE THREAD

**Issue by franetibe** [orbisgis/geoclimate#631]
Hello,

I have tried the bounding box approach with the BDTOPO v2.2 following the tutorial https://github.com/orbisgis/geoclimate/wiki/Bounding-box-case-%5BL%5D

I have used the config file of the tutorial, and I get the following error : 

java -jar geoclimate-0.0.1.jar -f my_first_config_file_bdtopov2_bb.json -w BDTOPO_V2.2
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Starting to process insee id_zone 6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335
Unable to find table PISTE_AERODROME
Unable to find table RESERVOIR
The  BD Topo data have been imported
Formating the BDTOPO data
The BD Topo data have been formated
BDTOPO V2 GIS layers formated
Start computing the geoindicators...
Create the units of analysis...
Loading graph into memory...
    0.004 seconds
Calculating connected components... 
    0.0 seconds
Storing node connected components... 
    0.0 seconds
Storing edge connected components...
    0.003 seconds
Start computing building indicators...
Start computing block indicators...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/Coding/Geoclimate/geoclimate-0.0.1.jar) to field java.util.ArrayList.size
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Start computing RSU indicators...
Processing urban typology surface fraction calculation
Processing LCZ surface fraction indicators calculation
Geoindicators calculation time: 0.296 s
All geoindicators have been computed
 The LCZ classification is performed 
 The URBAN TYPOLOGY classification is performed 
Error while executing the process.
 java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:226) ~[geoclimate-0.0.1.jar:?]
	at smile.data.DataFrame.of(DataFrame.java:1230) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame.of(DataFrame.java:1019) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.datamanager.dataframe.DataFrame$of.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.geoindicators.TypologyClassification$_applyRandomForestModel_closure3$_closure11.doCall(TypologyClassification.groovy:677) ~[geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[geoclimate-0.0.1.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) ~[geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators$_computeGeoclimateIndicators_closure6$_closure26.doCall(WorkflowGeoIndicators.groovy:1680) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1149) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators$_computeAllGeoIndicators_closure5$_closure19.doCall(WorkflowGeoIndicators.groovy:1476) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1149) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1149) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1149) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.bdtopo_processing(WorkflowBDTopo_V2.groovy:1330) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.bdtopo_processing(WorkflowBDTopo_V2.groovy) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2$_workflow_closure1$_closure21.doCall(WorkflowBDTopo_V2.groovy:324) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:83) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.access$1200(CommandLine.java:145) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2058) [geoclimate-0.0.1.jar:?]
	at picocli.CommandLine$execute.call(Unknown Source) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [geoclimate-0.0.1.jar:?]
Cannot apply the urban typology model URBAN_TYPOLOGY_BDTOPO_V2_RF_2_1.model
Cannot build the geoindicators
Cannot build the geoindicators for the zone 6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335
ZONE_1a4d9ccb_0e1c_46ad_a194_6224b5944311 has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/zones.geojson.
BUILDING has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/building.geojson.
ROAD has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/road.geojson.
RAIL has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/rail.geojson.
HYDRO has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/water.geojson.
VEGET has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/vegetation.geojson.
IMPERVIOUS has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/impervious.geojson.
grid_indicators has been saved in /tmp/bdtopo_v2_6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335/grid_indicators.geojson.
6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335 has been processed
The BDTOPO_V2.2 workflow has been successfully executed

I get the same error with linux and windows.

It looks like there is a problem with the UTRF calculation. Any idea where it comes from ?

Thanks !

**Comment by ebocher** [comment]
@ELSW56 
Can you test on Windows?

**Comment by j3r3m1** [comment]
It works for me on Linux. Do you use the geoclimate0.0.1 version ? I will test on Windows

**Comment by j3r3m1** [comment]
On Windows I have an error but not exactly the same as the @franetibe one:
> C:\Users\jeremy\Documents\GeoClimate>java -jar geoclimate-0.0.1.jar -f config_file_bdtopo_v2_bbox.json -w BDTOPO_V2.2
1 areas will be processed
Starting to process insee id_zone 6737756.724564202-316124.01010211144-6743486.0484706545-321921.09550058335
Unable to find table PISTE_AERODROME
Unable to find table RESERVOIR
The  BD Topo data have been imported
Formating the BDTOPO data
The BD Topo data have been formated
BDTOPO V2 GIS layers formated
Start computing the geoindicators...
Create the units of analysis...
Loading graph into memory...
    0.048 seconds
Calculating connected components...
    0.016 seconds
Storing node connected components...
    0.015 seconds
Storing edge connected components...
    0.203 seconds
Start computing building indicators...
Error while executing the process.
org.h2.jdbc.JdbcSQLNonTransientException: Exception calling user-defined function: "buffer(LINESTRING (316287.2 6742092.7, 316286.9 6742106, 316287.5 6742123.4, 316286.6 6742127.5, 316284.6 6742130.8, 316280.8 6742134.2, 316277.2 6742137.3, 316275.8 6742141.2, 316274.8 6742155.9, 316275.1 6742172.9), null, 'endcap=flat'): null"; SQL statement:
CREATE TABLE road_surf_f4150285_f2d4_4419_b760_7fcc9edeff18 AS
                    SELECT ST_BUFFER(the_geom, width::DOUBLE PRECISION/2,'endcap=flat') AS the_geom
                    FROM ROAD; [90105-200]

It has been run with geoclimate-0.0.1.

**Comment by j3r3m1** [comment]
Same kind of error if I use "Pont-de-Veyle" instead of its bounding box:
> org.h2.jdbc.JdbcSQLNonTransientException: Exception calling user-defined function: "buffer(LINESTRING (843773.5 6575684.9, 843757.9 6575690.3, 843679.2 6575714.1, 843657.5 6575719.5, 843643.9 6575721, 843629.2 6575723.2, 843616.5 6575723.8, 843597.3 6575723.1, 843578.3 6575722.5, 843566.9 6575722.5, 843557.7 6575723.6, 843550.1 6575725.8, 843541.2 6575729.2, 843533.9 6575732.4, 843507 6575741.8, 843458.3 6575757.8, 843452.5 6575759.6, 843442.7 6575762.6, 843429 6575767.6, 843424 6575770.8, 843420.3 6575775.5, 843419.6 6575776.5, 843413 6575783, 843405.2 6575789.3, 843403.2 6575789.9, 843400.5 6575790.8, 843396.3 6575791, 843391.4 6575790.4, 843386.5 6575789.2, 843381 6575786.5, 843303.3 6575739.2), null, 'endcap=flat'): null"; SQL statement:
                CREATE TABLE road_surf_f0aadc3b_bf86_4ac4_b89e_aa5c7720a35c AS
                    SELECT ST_BUFFER(the_geom, width::DOUBLE PRECISION/2,'endcap=flat') AS the_geom
                    FROM ROAD; [90105-200]
