### ISSUE TITLE
problem with the BDTOPO

### ISSUE THREAD

**Issue by gponche** [orbisgis/geoclimate#741]
Hello ! I have tested geoclimate with the BDTOPO V2, but when I execute this : java -jar Geoclimate.jar -f my_first_config_file_bdtopov2.json -w BDTOPO_V2.2  ; I have this message :
Unsupported file characters
Starting to process insee id_zone 54017-54064-54075-54421-54443-54488-54540-57003-57006-57011-57046-57064-57066-57071-57080-57083-57089-57091-57092-57100-57114-57119-57163-57168-57169-57180-57188-57192-57201-57210-57216-57
244-57248-57250-57255-57261-57263-57267-57280-57289-57291-57298-57300-57304-57308-57310-57315-57317-57324-57330-57333-57334-57335-57339-57346-57347-57355-57357-57366-57390-57407-57410-57418-57427-57456-57462-57468-57469-57
477-57489-57494-57499-57506-57518-57540-57541-57544-57551-57561-57566-57568-57581-57589-57592-57613-57618-57619-57623-57628-57629-57630-57631-57633-57635-57636-57658-57661-57680-57682-57703-57709-57711-57713-57721-57725-57
742-57745-57746-57747-57748-57750-57752-57760-57761-67001-67002-67003-67004-67005-67006-67008-67009-67010-67011-67012-67013-67016-67017-67018-67019-67020-67021-67022-67023-67025-67026-67027-67028-67029-67030-67031-67032-67
033-67034-67035-67036-67037-67038-67039-67040-67043-67044-67045-67046-67047-67048-67049-67050-67051-67052-67053-67054-67055-67056-67057-67058-67059-67060-67061-67062-67063-67065-67066-67067-67068-67069-67070-67071-67072-67
073-67074-67075-67076-67077-67078-67079-67080-67081-67082-67083-67084-67085-67086-67087-67088-67089-67090-67091-67092-67093-67094-67095-67096-67097-67098-67099-67100-67101-67102-67103-67104-67105-67106-67107-67108-67109-67
110-67111-67112-67113-67115-67116-67117-67118-67119-67120-67121-67122-67123-67124-67125-67126-67127-67128-67129-67130-67131-67132-67133-67134-67135-67136-67137-67138-67139-67140-67141-67142-67143-67144-67145-67146-67147-67
148-67149-67150-67151-67152-67153-67154-67155-67156-67159-67160-67161-67162-67163-67164-67165-67166-67167-67168-67169-67172-67173-67174-67176-67177-67178-67179-67180-67181-67182-67183-67184-67185-67186-67187-67188-67189-67
190-67191-67192-67194-67195-67196-67197-67198-67199-67200-67201-67202-67203-67204-67205-67206-67208-67209-67210-67212-67213-67214-67215-67216-67217-67218-67220-67221-67222-67223-67225-67226-67227-67228-67229-67230-67231-67
232-67233-67234-67235-67236-67237-67238-67239-67240-67241-67242-67244-67245-67246-67247-67248-67249-67250-67252-67253-67254-67255-67256-67257-67258-67259-67260-67261-67263-67264-67265-67266-67267-67268-67269-67270-67271-67
272-67273-67274-67275-67276-67277-67278-67279-67280-67281-67282-67283-67285-67286-67287-67288-67289-67290-67291-67292-67293-67295-67296-67298-67299-67300-67301-67302-67303-67304-67305-67306-67307-67308-67309-67310-67311-67
312-67313-67314-67315-67317-67319-67320-67321-67322-67324-67325-67326-67327-67328-67329-67330-67331-67333-67334-67335-67336-67337-67338-67339-67340-67341-67342-67343-67344-67345-67346-67347-67348-67349-67350-67351-67352-67
353-67354-67355-67356-67358-67359-67360-67361-67362-67363-67364-67365-67366-67367-67368-67369-67370-67371-67372-67373-67375-67377-67378-67379-67380-67381-67382-67383-67384-67385-67386-67387-67388-67389-67391-67392-67394-67
395-67396-67397-67398-67400-67401-67403-67404-67405-67406-67407-67408-67409-67410-67411-67412-67413-67414-67415-67416-67417-67418-67420-67421-67422-67423-67424-67425-67426-67427-67428-67429-67430-67432-67433-67434-67435-67
437-67438-67440-67441-67442-67443-67444-67445-67446-67447-67448-67449-67450-67451-67452-67453-67454-67455-67456-67458-67459-67460-67461-67462-67463-67464-67465-67466-67467-67468-67470-67471-67472-67473-67474-67475-67476-67
477-67478-67479-67480-67481-67482-67483-67484-67485-67486-67487-67488-67489-67490-67491-67492-67493-67494-67495-67497-67498-67499-67500-67501-67502-67503-67504-67505-67506-67507-67508-67509-67510-67511-67513-67514-67515-67
516-67517-67519-67520-67521-67522-67523-67524-67525-67526-67527-67528-67529-67530-67531-67532-67534-67535-67536-67537-67538-67539-67540-67541-67542-67543-67544-67545-67546-67547-67548-67550-67551-67552-67553-67554-67555-67
556-67557-67558-67559-68009-68019-68028-68066-68076-68110-68113-68143-68153-68157-68172-68185-68227-68252-68269-68280-68283-68285-68294-68296-68335-68345-68366-88005-88033-88053-88057-88093-88213-88215-88275-88276-88277-88
300-88306-88317-88320-88345-88361-88362-88373-88436-88444-88501-88503-88506-a
Error while executing the process.
java.lang.IllegalArgumentException: Cannot compare org.orbisgis.orbisdata.datamanager.jdbc.JdbcColumn with value 'org.orbisgis.orbisdata.datamanager.jdbc.JdbcColumn@63300c4b' and java.lang.Integer with value '0'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareToWithEqualityCheck(DefaultTypeTransformation.java:612) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.compareTo(DefaultTypeTransformation.java:541) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareTo(ScriptBytecodeAdapter.java:716) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.compareGreaterThan(ScriptBytecodeAdapter.java:766) ~[Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.InputDataLoading$_prepareBDTopoData_closure1$_closure4.doCall(InputDataLoading.groovy:153) ~[Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) ~[Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.call(Process.java:466) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2$_loadAndFormatData_closure20$_closure35.doCall(WorkflowBDTopo_V2.groovy:1974) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.bdtopo_processing(WorkflowBDTopo_V2.groovy:1289) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.bdtopo_processing(WorkflowBDTopo_V2.groovy) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2$_workflow_closure1$_closure21.doCall(WorkflowBDTopo_V2.groovy:324) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:83) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [Geoclimate.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [Geoclimate.jar:?]
	at picocli.CommandLine.access$1200(CommandLine.java:145) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [Geoclimate.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [Geoclimate.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2058) [Geoclimate.jar:?]
	at picocli.CommandLine$execute.call(Unknown Source) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [Geoclimate.jar:?]
Cannot import preprocess.
The BDTOPO_V2.2 workflow has been successfully executed
 Any idea ? 
Thank you

**Comment by j3r3m1** [comment]
Waou this is a really short list of insee codes =)
Have you tried with a much smaller number before ? Can you share your config file ?

**Comment by gponche** [comment]
Yes :
{
    "description": "Processing BDTOPO_V2.2",
    "input": {"bdtopo_v2": {
    	"folder": {	"path": "R:/home/mydirectory/Geoclimate/BDTOPO_V2.2/67000",
                   	"locations":[""]	}    }	 },
    "output": {   "folder": "R:/home/mydirectory/Geoclimate/BDTOPO_V2.2/output   },
    "parameters": {
        "rsu_indicators": { 
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
        "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}

**Comment by gponche** [comment]
when i try with just one commune (e.g strasbourg with the insee code : 67142), it didn't worked, I have this message : 
Error while executing the process.
groovy.json.JsonException: expecting '}' or ',' but got current char 'p' with an int value of 112

The current character read is 'p' with an int value of 112
expecting '}' or ',' but got current char 'p' with an int value of 112
line number 7
index number 301
    "parameters": {
.....^
	at org.apache.groovy.json.internal.JsonParserCharArray.complain(JsonParserCharArray.java:149) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:140) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeJsonObject(JsonParserCharArray.java:128) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:182) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:153) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:43) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:380) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:134) ~[Geoclimate.jar:?]
	at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:157) ~[Geoclimate.jar:?]
	at groovy.json.JsonSlurper.parseFile(JsonSlurper.java:385) ~[Geoclimate.jar:?]
	at groovy.json.JsonSlurper.parse(JsonSlurper.java:368) ~[Geoclimate.jar:?]
	at groovy.json.JsonSlurper$parse.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2.readJSONParameters(WorkflowBDTopo_V2.groovy:2051) ~[Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185) ~[Geoclimate.jar:?]
	at org.orbisgis.geoclimate.bdtopo_v2.WorkflowBDTopo_V2$_workflow_closure1$_closure21.doCall(WorkflowBDTopo_V2.groovy:157) ~[Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
	at groovy.lang.Closure.call(Closure.java:412) ~[Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
	at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:83) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [Geoclimate.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [Geoclimate.jar:?]
	at picocli.CommandLine.access$1200(CommandLine.java:145) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [Geoclimate.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [Geoclimate.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [Geoclimate.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2058) [Geoclimate.jar:?]
	at picocli.CommandLine$execute.call(Unknown Source) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
	at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [Geoclimate.jar:?]
Cannot execute the BDTOPO_V2.2 workflow
But I had change nothing on line of "parameters"

**Comment by j3r3m1** [comment]
I think troubles come from your json file. Please check that everything is well described. I have "formatted" your json and it seems a double quote is missing in the input path.

**Comment by gponche** [comment]
I have changed the double quote missing, now I have problem with the line 7, I have the message The current character read is '"' with an int value of 34
expecting '}' or ',' but got current char '"' with an int value of 34
line number 7
index number 299
	"parameters": 
But I have changed nothing on this line in my configuration file

**Comment by j3r3m1** [comment]
> 54017-54064-54075-54421-54443-54488-54540-57003-57006-57011-57046-57064-57066-57071-57080-57083-57089-57091-57092-57100-57114-57119-57163-57168-57169-57180-57188-57192-57201-57210-57216-57
244-57248-57250-57255-57261-57263-57267-57280-57289-57291-57298-57300-57304-57308-57310-57315-57317-57324-57330-57333-57334-57335-57339-57346-57347-57355-57357-57366-57390-57407-57410-57418-57427-57456-57462-57468-57469-57
477-57489-57494-57499-57506-57518-57540-57541-57544-57551-57561-57566-57568-57581-57589-57592-57613-57618-57619-57623-57628-57629-57630-57631-57633-57635-57636-57658-57661-57680-57682-57703-57709-57711-57713-57721-57725-57
742-57745-57746-57747-57748-57750-57752-57760-57761-67001-67002-67003-67004-67005-67006-67008-67009-67010-67011-67012-67013-67016-67017-67018-67019-67020-67021-67022-67023-67025-67026-67027-67028-67029-67030-67031-67032-67
033-67034-67035-67036-67037-67038-67039-67040-67043-67044-67045-67046-67047-67048-67049-67050-67051-67052-67053-67054-67055-67056-67057-67058-67059-67060-67061-67062-67063-67065-67066-67067-67068-67069-67070-67071-67072-67
073-67074-67075-67076-67077-67078-67079-67080-67081-67082-67083-67084-67085-67086-67087-67088-67089-67090-67091-67092-67093-67094-67095-67096-67097-67098-67099-67100-67101-67102-67103-67104-67105-67106-67107-67108-67109-67
110-67111-67112-67113-67115-67116-67117-67118-67119-67120-67121-67122-67123-67124-67125-67126-67127-67128-67129-67130-67131-67132-67133-67134-67135-67136-67137-67138-67139-67140-67141-67142-67143-67144-67145-67146-67147-67
148-67149-67150-67151-67152-67153-67154-67155-67156-67159-67160-67161-67162-67163-67164-67165-67166-67167-67168-67169-67172-67173-67174-67176-67177-67178-67179-67180-67181-67182-67183-67184-67185-67186-67187-67188-67189-67
190-67191-67192-67194-67195-67196-67197-67198-67199-67200-67201-67202-67203-67204-67205-67206-67208-67209-67210-67212-67213-67214-67215-67216-67217-67218-67220-67221-67222-67223-67225-67226-67227-67228-67229-67230-67231-67
232-67233-67234-67235-67236-67237-67238-67239-67240-67241-67242-67244-67245-67246-67247-67248-67249-67250-67252-67253-67254-67255-67256-67257-67258-67259-67260-67261-67263-67264-67265-67266-67267-67268-67269-67270-67271-67
272-67273-67274-67275-67276-67277-67278-67279-67280-67281-67282-67283-67285-67286-67287-67288-67289-67290-67291-67292-67293-67295-67296-67298-67299-67300-67301-67302-67303-67304-67305-67306-67307-67308-67309-67310-67311-67
312-67313-67314-67315-67317-67319-67320-67321-67322-67324-67325-67326-67327-67328-67329-67330-67331-67333-67334-67335-67336-67337-67338-67339-67340-67341-67342-67343-67344-67345-67346-67347-67348-67349-67350-67351-67352-67
353-67354-67355-67356-67358-67359-67360-67361-67362-67363-67364-67365-67366-67367-67368-67369-67370-67371-67372-67373-67375-67377-67378-67379-67380-67381-67382-67383-67384-67385-67386-67387-67388-67389-67391-67392-67394-67
395-67396-67397-67398-67400-67401-67403-67404-67405-67406-67407-67408-67409-67410-67411-67412-67413-67414-67415-67416-67417-67418-67420-67421-67422-67423-67424-67425-67426-67427-67428-67429-67430-67432-67433-67434-67435-67
437-67438-67440-67441-67442-67443-67444-67445-67446-67447-67448-67449-67450-67451-67452-67453-67454-67455-67456-67458-67459-67460-67461-67462-67463-67464-67465-67466-67467-67468-67470-67471-67472-67473-67474-67475-67476-67
477-67478-67479-67480-67481-67482-67483-67484-67485-67486-67487-67488-67489-67490-67491-67492-67493-67494-67495-67497-67498-67499-67500-67501-67502-67503-67504-67505-67506-67507-67508-67509-67510-67511-67513-67514-67515-67
516-67517-67519-67520-67521-67522-67523-67524-67525-67526-67527-67528-67529-67530-67531-67532-67534-67535-67536-67537-67538-67539-67540-67541-67542-67543-67544-67545-67546-67547-67548-67550-67551-67552-67553-67554-67555-67
556-67557-67558-67559-68009-68019-68028-68066-68076-68110-68113-68143-68153-68157-68172-68185-68227-68252-68269-68280-68283-68285-68294-68296-68335-68345-68366-88005-88033-88053-88057-88093-88213-88215-88275-88276-88277-88
300-88306-88317-88320-88345-88361-88362-88373-88436-88444-88501-88503-88506-

Are you sure you are executing the right config file ? It seems there is still a lot of insee codes ?
