### ISSUE TITLE
Geoclimate with OSM return empty folder

### ISSUE THREAD

**Issue by simonmarti1992** [orbisgis/geoclimate#756]
Dear Geoclimate users,
I'm facing an issue when I use Geoclimate with OpenStreetMap database. 
The code often (let say 50% of the time) return an empty folder with the following error
```
Error while executing the process.
java.lang.NumberFormatException: For input string: "Announced endpoint: lz4.overpass-api.de/api/"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_311]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_311]
        at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_311]
        at java.lang.Integer.decode(Unknown Source) ~[?:1.8.0_311]
        at java_lang_Integer$decode$0.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.OverpassStatus.<init>(OverpassStatus.groovy:87) ~[geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.getServerStatus(Utilities.groovy:602) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.executeOverPassQuery(Utilities.groovy:729) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$executeOverPassQuery$1.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisanalysis.osm.Loader$_extract_closure3$_closure7.doCall(Loader.groovy:249) ~[geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[geoclimate-0.0.1.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure20$_closure21.doCall(WorkflowOSM.groovy:492) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2234) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2214) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2264) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure20.doCall(WorkflowOSM.groovy:455) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_workflow_closure1$_closure17.doCall(WorkflowOSM.groovy:323) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [geoclimate-0.0.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [geoclimate-0.0.1.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:74) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine.access$1200(CommandLine.java:145) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:2058) [geoclimate-0.0.1.jar:?]
        at picocli.CommandLine$execute.call(Unknown Source) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [geoclimate-0.0.1.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [geoclimate-0.0.1.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [geoclimate-0.0.1.jar:?]
Cannot execute the overpass query [maxsize:1073741824][bbox:46.174101666666665,-1.1597015000000002,46.175923,-1.157942];
```

Does anybody facing the same issue ?

**Comment by bbrangeo** [comment]
I have same issue

**Comment by ebocher** [comment]
Dear @bbrangeo @simonmarti1992

Please share some informations about  the GeoClimate version  and the configuration file you are using

**Comment by bbrangeo** [comment]
Hello,

my config :

`{
  "description": "Processing OSM data",
  "input": {
    "osm": [
      [
        46.257330,
        4.870033,
        46.269970,
        4.905224
      ]
    ]
  },
  "output": {
    "folder": "./output",
    "srid": 4326
  },
  "parameters": {
    "rsu_indicators": {
      "indicatorUse": [
        "LCZ",
        "TEB",
        "UTRF"
      ],
      "svfSimplified": true,
      "estimateHeight": true
    },
    "grid_indicators": {
      "x_size": 100,
      "y_size": 100,
      "rowCol": false,
      "output": "geojson",
      "indicators": [
        "BUILDING_FRACTION",
        "BUILDING_HEIGHT",
        "BUILDING_TYPE_FRACTION",
        "WATER_FRACTION",
        "VEGETATION_FRACTION",
        "ROAD_FRACTION",
        "IMPERVIOUS_FRACTION",
        "URBAN_TYPO_AREA_FRACTION",
        "LCZ_FRACTION"
      ]
    }
  }
}`

and my version of geoclimate is 0.1

**Comment by ebocher** [comment]
Humm it seems an issue with overpass-api due to some changes in the URL.
Could you test with the last GeoClimate snapshot available here https://github.com/orbisgis/geoclimate/suites/7478858487/artifacts/306695490

Note : the config file has been modified. Please check the  documentation on the wiki

**Comment by bbrangeo** [comment]
Error :`[main] INFO org.orbisgis.geoclimate.osm.OSM - 1 osm areas will be processed
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/Users/Boris/Documents/TIPEE/SMART_RENO/API_SMART/geoclimate/geoclimate-0.0.2-SNAPSHOT.jar) to field java.util.ArrayList.size
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO org.orbisgis.geoclimate.osmtools.OSMTools - Extract the OSM data
[main] INFO org.orbisgis.geoclimate.osmtools.utils.Utilities - https://lz4.overpass-api.de/api/interpreter?data=%5Btimeout%3A900%5D%5Bmaxsize%3A1073741824%5D%5Bbbox%3A46.25733%2C4.870033%2C46.26997%2C4.905224%5D%3B%0A%28%28%0A%09node%5B%22building%22%5D%3B%0A%09node%5B%22railway%22%5D%3B%0A%09node%5B%22amenity%22%5D%3B%0A%09node%5B%22leisure%22%5D%3B%0A%09node%5B%22highway%22%5D%3B%0A%09node%5B%22natural%22%5D%3B%0A%09node%5B%22landuse%22%5D%3B%0A%09node%5B%22landcover%22%5D%3B%0A%09node%5B%22vegetation%22%5D%3B%0A%09node%5B%22waterway%22%5D%3B%0A%09way%5B%22building%22%5D%3B%0A%09way%5B%22railway%22%5D%3B%0A%09way%5B%22amenity%22%5D%3B%0A%09way%5B%22leisure%22%5D%3B%0A%09way%5B%22highway%22%5D%3B%0A%09way%5B%22natural%22%5D%3B%0A%09way%5B%22landuse%22%5D%3B%0A%09way%5B%22landcover%22%5D%3B%0A%09way%5B%22vegetation%22%5D%3B%0A%09way%5B%22waterway%22%5D%3B%0A%09relation%5B%22building%22%5D%3B%0A%09relation%5B%22railway%22%5D%3B%0A%09relation%5B%22amenity%22%5D%3B%0A%09relation%5B%22leisure%22%5D%3B%0A%09relation%5B%22highway%22%5D%3B%0A%09relation%5B%22natural%22%5D%3B%0A%09relation%5B%22landuse%22%5D%3B%0A%09relation%5B%22landcover%22%5D%3B%0A%09relation%5B%22vegetation%22%5D%3B%0A%09relation%5B%22waterway%22%5D%3B%0A%29%3B%0A%3E%3B%29%3B%0Aout%3B
[main] INFO org.orbisgis.geoclimate.osmtools.utils.Utilities - Executing query... [timeout:900][maxsize:1073741824][bbox:46.25733,4.870033,46.26997,4.905224];
((
	node["building"];
	node["railway"];
	node["amenity"];
	node["leisure"];
	node["highway"];
	node["natural"];
	node["landuse"];
	node["landcover"];
	node["vegetation"];
	node["waterway"];
	way["building"];
	way["railway"];
	way["amenity"];
	way["leisure"];
	way["highway"];
	way["natural"];
	way["landuse"];
	way["landcover"];
	way["vegetation"];
	way["waterway"];
	relation["building"];
	relation["railway"];
	relation["amenity"];
	relation["leisure"];
	relation["highway"];
	relation["natural"];
	relation["landuse"];
	relation["landcover"];
	relation["vegetation"];
	relation["waterway"];
);
>;);
out;
[main] ERROR org.orbisgis.geoclimate.osmtools.utils.Utilities - Cannot execute the query.
Connected as: 1603108662
Current time: 2022-08-24T10:23:40Z
Announced endpoint: lz4.overpass-api.de/api/
Rate limit: 3
3 slots available now.
Currently running queries (pid, space limit, time limit, start time):

[main] ERROR org.orbisgis.geoclimate.osmtools.OSMTools - Cannot extract the OSM data for the query [timeout:900][maxsize:1073741824][bbox:46.25733,4.870033,46.26997,4.905224];
((
	node["building"];
	node["railway"];
	node["amenity"];
	node["leisure"];
	node["highway"];
	node["natural"];
	node["landuse"];
	node["landcover"];
	node["vegetation"];
	node["waterway"];
	way["building"];
	way["railway"];
	way["amenity"];
	way["leisure"];
	way["highway"];
	way["natural"];
	way["landuse"];
	way["landcover"];
	way["vegetation"];
	way["waterway"];
	relation["building"];
	relation["railway"];
	relation["amenity"];
	relation["leisure"];
	relation["highway"];
	relation["natural"];
	relation["landuse"];
	relation["landcover"];
	relation["vegetation"];
	relation["waterway"];
);
>;);
out;
[main] ERROR org.orbisgis.geoclimate.osm.OSM - Cannot execute the overpass query [timeout:900][maxsize:1073741824][bbox:46.25733,4.870033,46.26997,4.905224];
((
	node["building"];
	node["railway"];
	node["amenity"];
	node["leisure"];
	node["highway"];
	node["natural"];
	node["landuse"];
	node["landcover"];
	node["vegetation"];
	node["waterway"];
	way["building"];
	way["railway"];
	way["amenity"];
	way["leisure"];
	way["highway"];
	way["natural"];
	way["landuse"];
	way["landcover"];
	way["vegetation"];
	way["waterway"];
	relation["building"];
	relation["railway"];
	relation["amenity"];
	relation["leisure"];
	relation["highway"];
	relation["natural"];
	relation["landuse"];
	relation["landcover"];
	relation["vegetation"];
	relation["waterway"];
);
>;);
out;`

java version is java version "11.0.16" 2022-07-19 LTS

**Comment by bbrangeo** [comment]
I find my error:

 "locations": [
            [
                46.257330,
                4.870033,
                46.269970,
                4.905224
            ]
        ],

to 

[46.257330,4.870033,46.269970,4.905224]

**Comment by bbrangeo** [comment]
Thanks

**Comment by simonmarti1992** [comment]
@bbrangeo @ebocher 
I just made the update, still I have an error for example with this bbox :
[46.178285, -1.1505603333333334, 46.1867825, -1.141033]
It seems that the maxsize and the timeout parameter causes the error. 
For example,
This request causes error : 
```
[timeout:900][maxsize:1073741824][bbox:46.178285,-1.1505603333333334,46.1867825,-1.141033];
((
        node["building"];
        node["railway"];
        node["amenity"];
        node["leisure"];
        node["highway"];
        node["natural"];
        node["landuse"];
        node["landcover"];
        node["vegetation"];
        node["waterway"];
        way["building"];
        way["railway"];
        way["amenity"];
        way["leisure"];
        way["highway"];
        way["natural"];
        way["landuse"];
        way["landcover"];
        way["vegetation"];
        way["waterway"];
        relation["building"];
        relation["railway"];
        relation["amenity"];
        relation["leisure"];
        relation["highway"];
        relation["natural"];
        relation["landuse"];
        relation["landcover"];
        relation["vegetation"];
        relation["waterway"];
);
>;);
out;
```
But this works fine 
```
[bbox:46.178285,-1.1505603333333334,46.1867825,-1.141033];
((
        node["building"];
        node["railway"];
        node["amenity"];
        node["leisure"];
        node["highway"];
        node["natural"];
        node["landuse"];
        node["landcover"];
        node["vegetation"];
        node["waterway"];
        way["building"];
        way["railway"];
        way["amenity"];
        way["leisure"];
        way["highway"];
        way["natural"];
        way["landuse"];
        way["landcover"];
        way["vegetation"];
        way["waterway"];
        relation["building"];
        relation["railway"];
        relation["amenity"];
        relation["leisure"];
        relation["highway"];
        relation["natural"];
        relation["landuse"];
        relation["landcover"];
        relation["vegetation"];
        relation["waterway"];
);
>;);
out;
```

**Comment by j3r3m1** [comment]
You can try to modify some of the values found here to allow a higher number of data to be downloaded:
https://github.com/orbisgis/geoclimate/wiki/Frequently-Asked-Questions#how-to-increase-the-size-of-the-data-downloaded-from-osm-
