### ISSUE TITLE
Error while executing the workflow

### ISSUE THREAD

**Issue by maxcollombin** [orbisgis/geoclimate#800]
When running the latest version of [Geoclimate](https://github.com/orbisgis/geoclimate/releases/download/0.0.1/geoclimate-0.0.1.jar) on Windows 10 with the basic configuration file as provided [here](https://github.com/orbisgis/geoclimate/releases/download/0.0.1/geoclimate-0.0.1.jar), I'm getting the following error: `Please set at least one OSM filter. e.g osm : ['A place name']`.
By changing the 'locations' parameter to 'osm', I can manage to run the script but get the following [error](https://gist.github.com/maxcollombin/b95e4c1fb0d1d76d66dc614824b52803).

PS I'm encountering the same issue while trying to run the script via WSL.

**Comment by j3r3m1** [comment]
> When running the latest version of [Geoclimate](https://github.com/orbisgis/geoclimate/releases/download/0.0.1/geoclimate-0.0.1.jar) on Windows 10 with the basic configuration file as provided [here](https://github.com/orbisgis/geoclimate/releases/download/0.0.1/geoclimate-0.0.1.jar), I'm getting the following error: `Please set at least one OSM filter. e.g osm : ['A place name']`. By changing the 'locations' parameter to 'osm', I can manage to run the script but get the following [error](https://gist.github.com/maxcollombin/b95e4c1fb0d1d76d66dc614824b52803).
> 
> PS I'm encountering the same issue while trying to run the script via WSL.

I think it should now be solved in the [last snapshot version](https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip) when using the config file displayed [in the wiki](https://github.com/orbisgis/geoclimate/wiki/Tutorials-for-Windows)

**Comment by maxcollombin** [comment]
Unfortunately not.
I'm still getting the following error:

```
 ERROR org.orbisgis.geoclimate.osm.OSM - The input parameters cannot be null or empty.
 Please set a path to a configuration file or a map with all required parameters
java.lang.NullPointerException: Cannot invoke method execute() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:79)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at picocli.CommandLine$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:119)
```

**Comment by magalietecher** [comment]
Hi, I have the same errors as yours. Did toi fond a solution finally? Thank you

**Comment by j3r3m1** [comment]
OK thank you for reporting, I also get the error on Linux. We need to find what is wrong.

**Comment by j3r3m1** [comment]
Should now be solved in the last snapshot version. Can you have a try please ?
https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip

**Comment by magalietecher** [comment]
Thank you! It works fine, i tested it with the basic configuration file for osm on WSL.
