### ISSUE TITLE
BUG! with Groovy console on a config file working with command line

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#811]
### Discussed in https://github.com/orbisgis/geoclimate/discussions/810

<div type='discussions-op-text'>

<sup>Originally posted by **GDDS2022** April 16, 2023</sup>
Hello,

I've got a config file working with command line, but when I use groovy console I(ve got this message:

BUG! exception in phase 'semantic analysis' in source unit 'ConsoleScript3' Unsupported class file major version 64

	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)

Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64

	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)

	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)

	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)

	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)

	at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)

	at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:124)

	... 1 more

Could it be from my java version?</div>

**Comment by j3r3m1** [comment]
@GDDS2022,, thank you for reporting.

What are your Java and groovy versions and what are the scripts you are using ?

**Comment by ebocher** [comment]
This issue was closed because it has been inactive since several days.
