### ISSUE TITLE
Run Geoclimate 0.0.1 on Windows 11

### ISSUE THREAD

**Issue by Paulo-le** [orbisgis/geoclimate#815]
Hi,
I use version 0.0.1 of GeoClimate on Windows 11.
I tried to launch it with the default config file and another one from a colleague (both are working on his computer) but it doesn't work.
This looks like issues #661 and #677 to me. 
Could you help me ?
Thanks
Paul

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
1 osm areas will be processed
https://nominatim.openstreetmap.org/search?q=Pont-de-Veyle&limit=5&format=geojson&polygon_geojson=1
Executing query... Pont-de-Veyle
Downloading the Nominatim data.
Error while executing the process.
groovy.lang.MissingPropertyException: Exception evaluating property 'size' for java.util.ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: size for class: java.math.BigDecimal
Possible solutions: scale
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAtIterable(DefaultGroovyMethods.java:8484) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:8472) ~[Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl$6.getProperty(MetaClassImpl.java:2071) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$_arrayToCoordinate_closure3.doCall(Utilities.groovy:177) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[Geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:428) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3562) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3547) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3647) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.dgm$101.invoke(Unknown Source) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.arrayToCoordinate(Utilities.groovy:176) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$arrayToCoordinate$2.callStatic(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:231) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.parsePolygon(Utilities.groovy:152) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$_getAreaFromPlace_closure1.doCall(Utilities.groovy:112) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:49) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:52) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.find(DefaultGroovyMethods.java:4355) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.dgm$233.invoke(Unknown Source) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities.getAreaFromPlace(Utilities.groovy:109) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisanalysis.osm.utils.Utilities$getAreaFromPlace.call(Unknown Source) ~[?:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[Geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM.extractOSMZone(WorkflowOSM.groovy:747) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203) ~[Geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure20$_closure21.doCall(WorkflowOSM.groovy:458) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2234) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2214) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.eachWithIndex(DefaultGroovyMethods.java:2264) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.dgm$213.invoke(Unknown Source) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[Geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_osm_processing_closure2$_closure20.doCall(WorkflowOSM.groovy:455) ~[Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[Geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) ~[Geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
        at org.orbisgis.geoclimate.osm.WorkflowOSM$_workflow_closure1$_closure17.doCall(WorkflowOSM.groovy:323) [Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
        at groovy.lang.Closure.call(Closure.java:412) [Geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.execute(Process.java:300) [Geoclimate.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) [Geoclimate.jar:?]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) [Geoclimate.jar:?]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:819) [Geoclimate.jar:?]
        at org.orbisgis.orbisdata.processmanager.process.Process.invokeMethod(Process.java:416) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:74) [Geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy) [Geoclimate.jar:?]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [Geoclimate.jar:?]
        at picocli.CommandLine.access$1200(CommandLine.java:145) [Geoclimate.jar:?]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [Geoclimate.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [Geoclimate.jar:?]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [Geoclimate.jar:?]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [Geoclimate.jar:?]
        at picocli.CommandLine.execute(CommandLine.java:2058) [Geoclimate.jar:?]
        at picocli.CommandLine$execute.call(Unknown Source) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [Geoclimate.jar:?]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) [Geoclimate.jar:?]
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:103) [Geoclimate.jar:?]
Cannot import the file : C:\Users\paull\AppData\Local\Temp\\logzones.geojson
Cannot execute the OSM workflow

**Comment by j3r3m1** [comment]
Hi @Paulo-le, you better have to download the 0.0.2-SNAPSHOT following the download page in the wiki: https://nightly.link/orbisgis/geoclimate/workflows/CI_snapshot/master/geoclimate-0.0.2-SNAPSHOT.zip

**Comment by Paulo-le** [comment]
Oh ! It was that simple ^^' 
Thanks a lot :)
