### ISSUE TITLE
Last version trouble

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#817]
It seems the last snapshot version of GeoClimate is bugged.

**Here is the command line run on a Windows machine:**
java -jar geoclimate-0.0.2-20230606.jar -f config_file_bdtv3_nantes.json -w BDTOPO_V3

**Here is the config file used:**
```json
{
    "description": "Processing BD Topo v2 data",
    "input": {
        "folder":"C:\\Users\\username\\Desktop\\Geoclimate\\BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D044_2022-03-15",
        "locations":["44109"]
				},
    "output": {
        "folder": "C:\\Users\\username\\Desktop\\Geoclimate\\geoclimate-0.0.2-SNAPSHOT\\output"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "URBAN_TYPOLOGY"
            ],
            "svfSimplified": false
        }
    }
}
```

**Here is the error obtained (same for BDTOPO v2):**
```
The BDTOPO_V3 workflow has been started.
Please wait...
groovy.lang.MissingMethodException: No signature of method: static org.orbisgis.geoclimate.Geoclimate.v3() is applicable for argument types: (String) values: [config_file_bdtv3_nantes.json]
Possible solutions: is(java.lang.Object), any(), tap(groovy.lang.Closure), use([Ljava.lang.Object;), any(groovy.lang.Closure), wait()
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1584)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1570)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1003)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
        at org.orbisgis.geoclimate.Geoclimate$BDTopo.$static_methodMissing(Geoclimate.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1582)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1570)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:113)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at picocli.CommandLine$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:133)

```

**Comment by ebocher** [comment]
Fixed in #819
