### ISSUE TITLE
Probable invalid geometry 

### ISSUE THREAD

**Issue by EmmanuelleKerjouan** [orbisgis/geoclimate#825]
In the Nancy study area, using BDTopo 2.2 or OpenStreetMap (OSM) data, we get this error message:  
Exception calling user-defined function: "isIntersects(POLYGON ((292458.4627341253 5397171.65263045, 292469.4837428904 5397176.787246137, 292466.52993751364 5397185.967035143, 292471.34284346807 5397187.60303075, 292472.22512055567 5397184.5654373, 292471.78524445946 5397184.425902638, 292473.14789674524 5397179.834672554, 292473.54239168187 5397179.942498351, 292482.6826801863 5397157.946416875, 292486.69440754515 5397159.634331002, 292499.05596788065 5397130.106897339, 292482.31604810024 5397123.147142348, 292479.12807025004 5397121.818278846, 292473.1246813367 5397136.397380551, 292464.9538119802 5397157.511766574, 292458.4627341253 5397171.65263045), (292468.0426444283 5397159.745773473, 292475.21698189806 5397140.771728635, 292476.21631044376 5397138.308535562, 292487.30267373356 5397143.0178525895, 292485.8634185282 5397145.141179754, 292484.97465820686 5397144.817923608, 292483.42719095736 5397145.6097245375, 292475.6865481263 5397164.014853308, 292468.0426444283 5397159.745773473), (292473.5624879603 5397140.0650201235, 292474.63580720226 5397137.610218247, 292476.21631044376 5397138.308535562, 292475.21698189806 5397140.771728635, 292473.5624879603 5397140.0650201235)), POLYGON ((289011.87857739284 5394391.885752221, 289188.7669394267 5399096.380824381, 294950.16002152907 5398882.649200651, 294778.1127344906 5394178.113384465, 289011.87857739284 5394391.885752221))): side location conflict [ (292475.21698189806, 5397140.771728635, NaN) ]";

The output UTM projection system for OSM data is 32631. 
For BDTopo 2.2 it is 2154. 
We suspect a regression as we get similar errors on cities where GeoClimate use to work without error (Toulouse on OSM for instance).

Do not hesitate to ask for more details if necessary.

**Comment by sfaraut** [comment]
Hello,
I also had this error on Nancy city with the previous Geoclimate version but with BDTOPO V3 workflow (BDTOPO_3-0_TOUSTHEMES_SHP_LAMB93_D054_2022-03-15) .
I just used the last snapshot downloaded today (apparently of 2023/07/18)  and error remains.

Here is the complete log:

C:\Users\faraut\Documents\DEVELOPPEMENT\Geoclimate>"C:\Program Files\Java\jdk-11.0.17\bin\java.exe" -jar geoclimate-0.0.2-SNAPSHOT-2023-07-18.jar -f config_Nancy_BDTOPOV3_2023-07-07.json -w BDTOPO_V3
The BDTOPO_V3 workflow has been started.
Please wait...
15:18:36.178 [main] INFO org.orbisgis.geoclimate.bdtopo.BDTopoUtils - Processing the commune with the code insee :  54395
15:18:50.518 [main] INFO org.orbisgis.geoclimate.bdtopo.BDTopoUtils - BDTOPO V2 GIS layers formated
15:18:50.550 [main] INFO org.orbisgis.geoclimate.Geoindicators - Create the units of analysis...
15:19:48.551 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing the geoindicators...
15:19:48.553 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing building indicators...
15:20:23.656 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing block indicators...
15:20:27.019 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing RSU indicators...
15:20:48.548 [main] INFO org.orbisgis.geoclimate.Geoindicators - Processing urban typology surface fraction calculation
15:20:48.558 [main] INFO org.orbisgis.geoclimate.Geoindicators - Processing LCZ surface fraction indicators calculation
15:20:49.079 [main] WARN org.orbisgis.geoclimate.Geoindicators -  The column pop doesn't exist or should be numeric
15:20:51.272 [main] INFO org.orbisgis.geoclimate.bdtopo.BDTopoUtils - Processing the commune with the code insee :  54395
15:20:59.376 [main] INFO org.orbisgis.geoclimate.bdtopo.BDTopoUtils - BDTOPO V2 GIS layers formated
15:20:59.377 [main] INFO org.orbisgis.geoclimate.Geoindicators - Create the units of analysis...
15:21:53.554 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing the geoindicators...
15:21:53.554 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing building indicators...
15:22:28.186 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing block indicators...
15:22:31.005 [main] INFO org.orbisgis.geoclimate.Geoindicators - Start computing RSU indicators...
15:22:53.134 [main] INFO org.orbisgis.geoclimate.Geoindicators - Processing urban typology surface fraction calculation
15:22:53.139 [main] INFO org.orbisgis.geoclimate.Geoindicators - Processing LCZ surface fraction indicators calculation
15:22:53.932 [main] WARN org.orbisgis.geoclimate.Geoindicators -  The column pop doesn't exist or should be numeric
org.h2.jdbc.JdbcSQLNonTransientException: Exception lors de l'appel de la fonction définie par l'utilisateur: "isIntersects(POLYGON ((932145.6 6849467, 932192 6849488.2, 932219.9 6849501.9, 932230.5 6849507.1, 932260.7 6849522.2, 932265 6849525.1, 932266 6849526.9, 932266.7 6849529.3, 932266.6 6849532.2, 932265.6 6849534.8, 932239 6849588.1, 932232.1 6849601.9, 932210.2 6849645.8, 932204.5 6849658.1, 932195 6849654.3, 932193.6 6849658.5, 932191.4 6849662.6, 932188.2 6849666.7, 932180.7 6849677, 932167.6 6849694.9, 932159 6849702.7, 932170.1 6849714.3, 932158.4 6849724.5, 932162.3452798094 6849729.135355254, 932165.4 6849727.5, 932184.6 6849717.5, 932202.5 6849713.7, 932206.5 6849712.7, 932240 6849705.7, 932241.1 6849705.6, 932289.9 6849701.2, 932249.9132117241 6849704.805366156, 932250 6849704.5, 932249.3 6849699, 932252.3 6849695.5, 932256 6849688.3, 932263.5 6849689, 932266 6849688.3, 932273.3 6849682, 932275 6849679.3, 932280.5 6849678.3, 932282.8 6849676.5, 932284 6849673.3, 932283 6849669.3, 932285 6849668.3, 932291.8 6849662, 932297 6849653.6, 932302.3 6849645, 932306.8 6849635, 932309.8 6849621, 932310 6849605.8, 932308.3 6849601, 932305 6849558.3, 932307.5 6849557.3, 932308.3 6849556.5, 932309 6849552.5, 932311.5 6849547.5, 932309.3 6849543, 932308.8 6849537.5, 932307 6849535.3, 932305.3 6849534, 932304.8 6849528, 932304 6849525.5, 932306.8 6849521, 932313 6849506.3, 932312.3 6849503.5, 932311 6849501.5, 932313.8 6849493, 932314 6849488.3, 932315.9 6849486.8, 932316.0818181818 6849486.663636364, 932315.1 6849484.7, 932315.2 6849480.8, 932316.2 6849477.2, 932318.4 6849472.8, 932321 6849467.2, 932325.6 6849458.1, 932330.3 6849448.6, 932323.2 6849444.9, 932314.4 6849440.8, 932306.4 6849437.1, 932302 6849435, 932299.1 6849440.5, 932296.7 6849444.7, 932295.3 6849448.9, 932294 6849453.4, 932294.6 6849458.3, 932290.3 6849458.8, 932286.1 6849457.5, 932281.3 6849455.3, 932275.9 6849452.8, 932270.2 6849449.8, 932264.9 6849446.8, 932259.9 6849443.9, 932254.6 6849441.2, 932249.3 6849438.9, 932244.4 6849437, 932239.8 6849436.3, 932235.8 6849437.7, 932234.4 6849439.4, 932233.4 6849440.8, 932231.5 6849444.3, 932229.4 6849448.6, 932227.1 6849453.2, 932225.3 6849457.1, 932220.7 6849466.4, 932169.6 6849441.1, 932162.9 6849439.1, 932154.1 6849448.4, 932151.4 6849453.8, 932148.7 6849459.9, 932145.6 6849467)), LINESTRING (932289.8830790567 6849701.201525659, 932289.9 6849701.1, 932290.4 6849698.5, 932294.1 6849688.2, 932297.8 6849679.3, 932298.2 6849678.5, 932301.4 6849673.4, 932305.4 6849668.5, 932311.3 6849660.5, 932316.5 6849652.5)): side location conflict [ (932289.8830790567, 6849701.201525659, NaN) ]"
Exception calling user-defined function: "isIntersects(POLYGON ((932145.6 6849467, 932192 6849488.2, 932219.9 6849501.9, 932230.5 6849507.1, 932260.7 6849522.2, 932265 6849525.1, 932266 6849526.9, 932266.7 6849529.3, 932266.6 6849532.2, 932265.6 6849534.8, 932239 6849588.1, 932232.1 6849601.9, 932210.2 6849645.8, 932204.5 6849658.1, 932195 6849654.3, 932193.6 6849658.5, 932191.4 6849662.6, 932188.2 6849666.7, 932180.7 6849677, 932167.6 6849694.9, 932159 6849702.7, 932170.1 6849714.3, 932158.4 6849724.5, 932162.3452798094 6849729.135355254, 932165.4 6849727.5, 932184.6 6849717.5, 932202.5 6849713.7, 932206.5 6849712.7, 932240 6849705.7, 932241.1 6849705.6, 932289.9 6849701.2, 932249.9132117241 6849704.805366156, 932250 6849704.5, 932249.3 6849699, 932252.3 6849695.5, 932256 6849688.3, 932263.5 6849689, 932266 6849688.3, 932273.3 6849682, 932275 6849679.3, 932280.5 6849678.3, 932282.8 6849676.5, 932284 6849673.3, 932283 6849669.3, 932285 6849668.3, 932291.8 6849662, 932297 6849653.6, 932302.3 6849645, 932306.8 6849635, 932309.8 6849621, 932310 6849605.8, 932308.3 6849601, 932305 6849558.3, 932307.5 6849557.3, 932308.3 6849556.5, 932309 6849552.5, 932311.5 6849547.5, 932309.3 6849543, 932308.8 6849537.5, 932307 6849535.3, 932305.3 6849534, 932304.8 6849528, 932304 6849525.5, 932306.8 6849521, 932313 6849506.3, 932312.3 6849503.5, 932311 6849501.5, 932313.8 6849493, 932314 6849488.3, 932315.9 6849486.8, 932316.0818181818 6849486.663636364, 932315.1 6849484.7, 932315.2 6849480.8, 932316.2 6849477.2, 932318.4 6849472.8, 932321 6849467.2, 932325.6 6849458.1, 932330.3 6849448.6, 932323.2 6849444.9, 932314.4 6849440.8, 932306.4 6849437.1, 932302 6849435, 932299.1 6849440.5, 932296.7 6849444.7, 932295.3 6849448.9, 932294 6849453.4, 932294.6 6849458.3, 932290.3 6849458.8, 932286.1 6849457.5, 932281.3 6849455.3, 932275.9 6849452.8, 932270.2 6849449.8, 932264.9 6849446.8, 932259.9 6849443.9, 932254.6 6849441.2, 932249.3 6849438.9, 932244.4 6849437, 932239.8 6849436.3, 932235.8 6849437.7, 932234.4 6849439.4, 932233.4 6849440.8, 932231.5 6849444.3, 932229.4 6849448.6, 932227.1 6849453.2, 932225.3 6849457.1, 932220.7 6849466.4, 932169.6 6849441.1, 932162.9 6849439.1, 932154.1 6849448.4, 932151.4 6849453.8, 932148.7 6849459.9, 932145.6 6849467)), LINESTRING (932289.8830790567 6849701.201525659, 932289.9 6849701.1, 932290.4 6849698.5, 932294.1 6849688.2, 932297.8 6849679.3, 932298.2 6849678.5, 932301.4 6849673.4, 932305.4 6849668.5, 932311.3 6849660.5, 932316.5 6849652.5)): side location conflict [ (932289.8830790567, 6849701.201525659, NaN) ]"; SQL statement:
DROP TABLE IF EXISTS roadInter_0d5a65ba_5487_436d_b6d7_225055a5c44a [90105-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.message.DbException.convertInvocation(DbException.java:424)
        at org.h2.schema.FunctionAlias$JavaMethod.execute(FunctionAlias.java:508)
        at org.h2.schema.FunctionAlias$JavaMethod.getValue(FunctionAlias.java:345)
        at org.h2.expression.function.JavaFunction.getValue(JavaFunction.java:40)
        at org.h2.expression.condition.ConditionAndOrN.getValue(ConditionAndOrN.java:128)
        at org.h2.expression.Expression.getBooleanValue(Expression.java:332)
        at org.h2.command.query.Select.isConditionMet(Select.java:449)
        at org.h2.command.query.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1835)
        at org.h2.result.LazyResult.hasNext(LazyResult.java:78)
        at org.h2.result.FetchedResult.next(FetchedResult.java:34)
        at org.h2.command.query.Select.queryFlat(Select.java:728)
        at org.h2.command.query.Select.queryWithoutCache(Select.java:833)
        at org.h2.command.query.Query.queryWithoutCacheLazyCheck(Query.java:197)
        at org.h2.command.query.Query.query(Query.java:512)
        at org.h2.command.dml.Insert.insertRows(Insert.java:197)
        at org.h2.command.dml.Insert.update(Insert.java:135)
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74)
        at org.h2.command.ddl.CreateTable.update(CreateTable.java:175)
        at org.h2.command.CommandContainer.update(CommandContainer.java:169)
        at org.h2.command.CommandList.executeRemaining(CommandList.java:58)
        at org.h2.command.CommandList.update(CommandList.java:66)
        at org.h2.command.Command.executeUpdate(Command.java:252)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
        at org.h2.jdbc.JdbcCallableStatement.executeUpdate(JdbcCallableStatement.java:96)
        at groovy.sql.Sql.call(Sql.java:3068)
        at groovy.sql.Sql.call(Sql.java:3014)
        at groovy.sql.Sql$call$1.call(Unknown Source)
        at org.orbisgis.geoclimate.geoindicators.RsuIndicators.linearRoadOperations(RsuIndicators.groovy:976)
        at org.orbisgis.geoclimate.geoindicators.RsuIndicators$linearRoadOperations$2.call(Unknown Source)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators.computeRSUIndicators(WorkflowGeoIndicators.groovy:609)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators$computeRSUIndicators$4.callCurrent(Unknown Source)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators.computeGeoclimateIndicators(WorkflowGeoIndicators.groovy:1529)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators$computeGeoclimateIndicators$1.callCurrent(Unknown Source)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators.computeAllGeoIndicators(WorkflowGeoIndicators.groovy:1334)
        at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators$computeAllGeoIndicators.call(Unknown Source)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.bdTopoProcessingSingleArea(AbstractBDTopoWorkflow.groovy:928)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow$_bdtopo_processing_closure9.doCall(AbstractBDTopoWorkflow.groovy:691)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at groovy.sql.Sql.eachRow(Sql.java:1228)
        at groovy.sql.Sql.eachRow(Sql.java:1182)
        at groovy.sql.Sql.eachRow(Sql.java:1119)
        at org.orbisgis.data.jdbc.JdbcDataSource.eachRow(JdbcDataSource.java:532)
        at org.orbisgis.data.jdbc.JdbcDataSource$eachRow.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.bdtopo_processing(AbstractBDTopoWorkflow.groovy:677)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.bdtopo_processing(AbstractBDTopoWorkflow.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow$_execute_closure1.doCall(AbstractBDTopoWorkflow.groovy:237)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:428)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2359)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2397)
        at org.codehaus.groovy.runtime.dgm$204.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.execute(AbstractBDTopoWorkflow.groovy:231)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.bdtopo.BDTopo.v3(BDTopo.groovy:165)
        at org.orbisgis.geoclimate.bdtopo.BDTopo$v3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:113)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at picocli.CommandLine$execute.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:133)
Caused by: org.locationtech.jts.geom.TopologyException: side location conflict [ (932289.8830790567, 6849701.201525659, NaN) ]
        at org.locationtech.jts.geomgraph.EdgeEndStar.propagateSideLabels(EdgeEndStar.java:289)
        at org.locationtech.jts.geomgraph.EdgeEndStar.computeLabelling(EdgeEndStar.java:125)
        at org.locationtech.jts.operation.relate.RelateComputer.labelNodeEdges(RelateComputer.java:325)
        at org.locationtech.jts.operation.relate.RelateComputer.computeIM(RelateComputer.java:125)
        at org.locationtech.jts.operation.relate.RelateOp.getIntersectionMatrix(RelateOp.java:109)
        at org.locationtech.jts.operation.relate.RelateOp.relate(RelateOp.java:54)
        at org.locationtech.jts.geom.Geometry.relate(Geometry.java:1035)
        at org.locationtech.jts.geom.Geometry.intersects(Geometry.java:767)
        at org.h2gis.functions.spatial.predicates.ST_Intersects.isIntersects(ST_Intersects.java:60)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.h2.schema.FunctionAlias$JavaMethod.execute(FunctionAlias.java:495)
        ... 119 more

To complete the initial issue, I'm using Windows JAVA11 (11.0.17) and Geoclimate is working properly on Toulouse center (3155) with BDTOPO...

Thanks by advance for your help.

**Comment by ebocher** [comment]
Thanks we will check it.

**Comment by ebocher** [comment]
Please test. It seems fixed in Master

**Comment by ebocher** [comment]
Fixed on current master
