### ISSUE TITLE
 ERROR org.orbisgis.data.H2GIS - Unable to find table null

### ISSUE THREAD

**Issue by BenjaminSOLENEOS** [orbisgis/geoclimate#968]
Bonjour, 

J'ai lancé geoclimate (geoclimate-1.0.1-SNAPSHOT.jar) sur une partie de la métropole de Rouen et j'ai une erreur. 
 
Voici le fichier de config : 
```
{
    "description": "Processing BDTopo v3 data",
    "input": {
        "folder":  "/home/soleneos/Documents/PLU_Rouen/BD_TOPO_V3/",
"locations":["76005","76020"],
        "srid":2154
    },
    "output": {
        "folder": "/media/soleneos/Elements/GeoclimateData/"
    },
    "parameters": {
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :["FREE_EXTERNAL_FACADE_DENSITY"
                               ]
         }
    }
}
```
Voici la commande utilisée : 

`java -jar geoclimate-1.0.1-SNAPSHOT.jar -f my_first_config_file_bdtopov2_box_bis.json -w BDTOPO_V3`

Et voici l'erreur : 

```
The BDTOPO_V3 workflow has been started.
Please wait...
[main] INFO GeoClimate - Processing the commune with the code insee :  76005
[main] INFO GeoClimate - Formating BDTopo GIS layers
[main] INFO GeoClimate - Impervious areas formatted
[main] INFO GeoClimate - Building formatted
[main] INFO GeoClimate - Road formatted
[main] INFO GeoClimate - Rail formatted
[main] INFO GeoClimate - Vegetation formatted
[main] INFO GeoClimate - Water formatted
[main] INFO GeoClimate - All layers have been formatted
[main] INFO GeoClimate - BDTOPO GIS layers formated
[main] INFO GeoClimate - 76005 has been processed
[main] INFO GeoClimate - Start computing grid_indicators
[main] ERROR org.orbisgis.data.H2GIS - Unable to find table null
groovy.lang.MissingPropertyException: No such property: null for class: org.orbisgis.data.H2GIS
Possible solutions: NULL
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.geoindicators.WorkflowGeoIndicators.rasterizeIndicators(WorkflowGeoIndicators.groovy:2030)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.computeGridIndicators(AbstractBDTopoWorkflow.groovy:855)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.bdtopo_processing(AbstractBDTopoWorkflow.groovy:751)
	at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.bdtopo_processing(AbstractBDTopoWorkflow.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:342)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1008)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow$_execute_closure1.doCall(AbstractBDTopoWorkflow.groovy:237)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1008)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:422)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2389)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2374)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2427)
	at org.codehaus.groovy.runtime.dgm$209.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.execute(AbstractBDTopoWorkflow.groovy:231)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.bdtopo.BDTopo.v3(BDTopo.groovy:167)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:114)
	at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:134)
```

**Comment by j3r3m1** [comment]
Thanks for the information. What is the version of BDTopo V3 you are using ? V3.3 ? Or any date you may have coming along the data ?

**Comment by BenjaminSOLENEOS** [comment]
Arg... I forget this information : "BDT_3-3_SHP_LAMB93_D076-ED2024-03-15" that i download there : https://data.geopf.fr/telechargement/download/BDTOPO/BDTOPO_3-3_TOUSTHEMES_SHP_LAMB93_D076_2024-03-15/BDTOPO_3-3_TOUSTHEMES_SHP_LAMB93_D076_2024-03-15.7z

**Comment by j3r3m1** [comment]
Should be solved with #970. Feel free to reopen if this is not the case
