### ISSUE TITLE
Save Log Zone Table error when processing BDTopoV3 in Bounding Box

### ISSUE THREAD

**Issue by Jukjuk-boop** [orbisgis/geoclimate#988]
I tried to run geoclimate in a bounding box with the BDTopoV3 Data.
I'm stuck on the error bellow :
[main] INFO GeoClimate - 21179 has been processed
groovy.lang.MissingMethodException: No signature of method: org.orbisgis.geoclimate.bdtopo.BDTopoV3Workflow.saveLogZoneTable() is applicable for argument types: (org.orbisgis.data.H2GIS, String, ArrayList, String) values: [org.orbisgis.data.H2GIS@3fca4264, C:\Users\Juk\AppData\Local\Temp\, ...]
Possible solutions: saveLogZoneTable(org.orbisgis.data.jdbc.JdbcDataSource, java.lang.String, java.lang.String, java.lang.String)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:72)
        at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow$_execute_closure1.doCall(AbstractBDTopoWorkflow.groovy:223)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1008)
        at groovy.lang.Closure.call(Closure.java:433)
        at groovy.lang.Closure.call(Closure.java:422)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2389)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2374)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2427)
        at org.codehaus.groovy.runtime.dgm$209.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at org.orbisgis.geoclimate.bdtopo.AbstractBDTopoWorkflow.execute(AbstractBDTopoWorkflow.groovy:208)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at org.orbisgis.geoclimate.bdtopo.BDTopo.v3(BDTopo.groovy:162)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy:114)
        at org.orbisgis.geoclimate.Geoclimate.call(Geoclimate.groovy)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
        at org.orbisgis.geoclimate.Geoclimate.main(Geoclimate.groovy:134)

I tried to decrease the bounding box size (modifying coordinates from 6679000,841300,6709000,868500 to 6690000,850000,6709000,855000) but the same error occurs.
I have already gone through the process Succesfully with a "light" config file as below :
{
    "description": "Processing BDT data",
    "input": {
    	"area" : 100000,
	"srid": 2154,
    	"folder": "C://Users/Juk/Desktop/memoire/Geoclimate/Dijon/Data/BDTopoV3",
        "locations": [
            [6679000,841300,6709000,868500]
        ]
    },
    "output": {
        "folder": "/tmp"
    },
    "parameters": {
        "rsu_indicators": {
	"output" : "geojson",
            "indicatorUse": [
                "LCZ"
            ]
        }
    }
}

The error show in this issue only show up with the "full" config :
{
    "description": "Processing BDT data",
    "input": {
    	"area" : 100000,
	"srid": 2154,
    	"folder": "C://Users/Juk/Desktop/memoire/Geoclimate/Dijon/Data/BDTopoV3",
        "locations": [
            [6679000,841300,6709000,868500]
        ]
    },
    "output": {
        "folder": "/tmp"
    },
    "parameters": {
        "rsu_indicators": {
            "indicatorUse": [
                "LCZ",
                "TEB",
                "UTRF"
            ],
            "svfSimplified": true
        },
        "grid_indicators": {
            "x_size": 100,
	    "y_size": 100,
	    "rowCol": false,
	    "output" : "geojson",
	    "indicators" :[
                 "BUILDING_FRACTION", 
                 "BUILDING_HEIGHT", 
                 "WATER_FRACTION",
                 "VEGETATION_FRACTION", 
                 "ROAD_FRACTION", 
                 "IMPERVIOUS_FRACTION", 
                 "LCZ_FRACTION"
             ]
         }
    }
}

**Comment by ebocher** [comment]
Thanks It will be fixed in this PR #989
